import { z } from "zod";

const environmentSchema = z.object({
  DATABASE_URL: z.string().url().or(z.string().startsWith("postgresql://")).default("postgresql://pramana:pramana@localhost:5432/pramana"),
  AUTH_MODE: z.enum(["development", "credentials", "clerk"]).default("development"),
  AUTH_ENCRYPTION_KEY: z.string().min(32).optional(),
  SESSION_COOKIE_NAME: z.string().min(1).default("pramana_session"),
  SESSION_TTL_HOURS: z.coerce.number().int().min(1).max(720).default(24),
  APP_BASE_URL: z.string().url().default("http://localhost:4173"),
  INGESTION_SERVICE_URL: z.string().url().default("http://localhost:8001"),
  SOLVER_SERVICE_URL: z.string().url().default("http://localhost:8002"),
  LOCAL_UPLOAD_DIR: z.string().min(1).default("./data/uploads"),
  OBJECT_STORAGE_DRIVER: z.enum(["local", "s3"]).default("local"),
  S3_ENDPOINT: z.string().url().default("http://localhost:9000"),
  S3_REGION: z.string().min(1).default("us-east-1"),
  S3_ACCESS_KEY: z.string().min(1).default("minioadmin"),
  S3_SECRET_KEY: z.string().min(1).default("minioadmin"),
  S3_BUCKET: z.string().min(3).default("pramana-local"),
  REDIS_URL: z.string().url().default("redis://localhost:6379"),
  REDIS_PREFIX: z.string().min(1).default("pramana"),
  INFRA_ALLOW_DEGRADED: z.enum(["true", "false"]).default("true").transform((value) => value === "true"),
  MODEL_PROVIDER: z.enum(["mock", "gemini", "nim"]).default("mock"),
  GEMINI_API_KEY: z.string().optional(),
  GEMINI_MODEL: z.string().min(1).default("gemini-2.5-flash"),
  NIM_BASE_URL: z.string().url().default("https://integrate.api.nvidia.com/v1"),
  NIM_API_KEY: z.string().optional(),
  NIM_MODEL: z.string().min(1).default("meta/llama-3.3-70b-instruct"),
  EMBEDDING_PROVIDER: z.enum(["mock", "service"]).default("mock"),
  RETRIEVAL_SERVICE_URL: z.string().url().default("http://localhost:8003"),
  SHIPMENT_STATUS_BUFFER_HOURS: z.coerce.number().min(0).max(720).default(72),
  POLL_INTERVAL_MS: z.coerce.number().int().min(1_000).max(3_600_000).default(60_000),
  POLL_ENABLED: z.enum(["true", "false"]).default("true").transform((value) => value === "true"),
  AIS_MODE: z.enum(["synthetic", "aisstream"]).default("synthetic"),
  AISSTREAM_API_KEY: z.string().optional(),
  WEATHER_MODE: z.enum(["synthetic", "open-meteo"]).default("synthetic"),
  OPEN_METEO_BASE_URL: z.string().url().default("https://marine-api.open-meteo.com/v1/marine"),
  RISK_POLL_MODE: z.enum(["synthetic", "http"]).default("synthetic"),
  RISK_PROBABILITY_THRESHOLD: z.coerce.number().min(0).max(1).default(0.5),
  RISK_DELAY_HOURS_THRESHOLD: z.coerce.number().int().min(1).max(2160).default(8),
  RISK_PROCUREMENT_URL: z.string().url().optional(),
  RISK_LEAD_TIME_URL: z.string().url().optional(),
  RISK_WORKFORCE_URL: z.string().url().optional(),
  RISK_WEATHER_URL: z.string().url().optional(),
  RISK_SITE_LAT: z.coerce.number().min(-90).max(90).default(18.9492),
  RISK_SITE_LNG: z.coerce.number().min(-180).max(180).default(72.9347),
  KNOWLEDGE_SIMILARITY_THRESHOLD: z.coerce.number().min(0).max(1).default(0.2),
  AI_RATE_LIMIT: z.coerce.number().int().min(1).max(100_000).default(60),
  AI_RATE_LIMIT_WINDOW_SECONDS: z.coerce.number().int().min(1).max(3_600).default(60),
  NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: z.string().optional(),
  CLERK_SECRET_KEY: z.string().optional()
});

export const env = environmentSchema.parse({
  DATABASE_URL: process.env.DATABASE_URL,
  AUTH_MODE: process.env.AUTH_MODE,
  AUTH_ENCRYPTION_KEY: process.env.AUTH_ENCRYPTION_KEY,
  SESSION_COOKIE_NAME: process.env.SESSION_COOKIE_NAME,
  SESSION_TTL_HOURS: process.env.SESSION_TTL_HOURS,
  APP_BASE_URL: process.env.APP_BASE_URL,
  INGESTION_SERVICE_URL: process.env.INGESTION_SERVICE_URL,
  SOLVER_SERVICE_URL: process.env.SOLVER_SERVICE_URL,
  LOCAL_UPLOAD_DIR: process.env.LOCAL_UPLOAD_DIR,
  OBJECT_STORAGE_DRIVER: process.env.OBJECT_STORAGE_DRIVER,
  S3_ENDPOINT: process.env.S3_ENDPOINT,
  S3_REGION: process.env.S3_REGION,
  S3_ACCESS_KEY: process.env.S3_ACCESS_KEY,
  S3_SECRET_KEY: process.env.S3_SECRET_KEY,
  S3_BUCKET: process.env.S3_BUCKET,
  REDIS_URL: process.env.REDIS_URL,
  REDIS_PREFIX: process.env.REDIS_PREFIX,
  INFRA_ALLOW_DEGRADED: process.env.INFRA_ALLOW_DEGRADED,
  MODEL_PROVIDER: process.env.MODEL_PROVIDER,
  GEMINI_API_KEY: process.env.GEMINI_API_KEY,
  GEMINI_MODEL: process.env.GEMINI_MODEL,
  NIM_BASE_URL: process.env.NIM_BASE_URL,
  NIM_API_KEY: process.env.NIM_API_KEY,
  NIM_MODEL: process.env.NIM_MODEL,
  EMBEDDING_PROVIDER: process.env.EMBEDDING_PROVIDER,
  RETRIEVAL_SERVICE_URL: process.env.RETRIEVAL_SERVICE_URL,
  SHIPMENT_STATUS_BUFFER_HOURS: process.env.SHIPMENT_STATUS_BUFFER_HOURS,
  POLL_INTERVAL_MS: process.env.POLL_INTERVAL_MS,
  POLL_ENABLED: process.env.POLL_ENABLED,
  AIS_MODE: process.env.AIS_MODE,
  AISSTREAM_API_KEY: process.env.AISSTREAM_API_KEY,
  WEATHER_MODE: process.env.WEATHER_MODE,
  OPEN_METEO_BASE_URL: process.env.OPEN_METEO_BASE_URL,
  RISK_POLL_MODE: process.env.RISK_POLL_MODE,
  RISK_PROBABILITY_THRESHOLD: process.env.RISK_PROBABILITY_THRESHOLD,
  RISK_DELAY_HOURS_THRESHOLD: process.env.RISK_DELAY_HOURS_THRESHOLD,
  RISK_PROCUREMENT_URL: process.env.RISK_PROCUREMENT_URL,
  RISK_LEAD_TIME_URL: process.env.RISK_LEAD_TIME_URL,
  RISK_WORKFORCE_URL: process.env.RISK_WORKFORCE_URL,
  RISK_WEATHER_URL: process.env.RISK_WEATHER_URL,
  RISK_SITE_LAT: process.env.RISK_SITE_LAT,
  RISK_SITE_LNG: process.env.RISK_SITE_LNG,
  KNOWLEDGE_SIMILARITY_THRESHOLD: process.env.KNOWLEDGE_SIMILARITY_THRESHOLD,
  AI_RATE_LIMIT: process.env.AI_RATE_LIMIT,
  AI_RATE_LIMIT_WINDOW_SECONDS: process.env.AI_RATE_LIMIT_WINDOW_SECONDS,
  NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY,
  CLERK_SECRET_KEY: process.env.CLERK_SECRET_KEY
});

export const clerkIsConfigured = env.AUTH_MODE === "clerk" && Boolean(env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY && env.CLERK_SECRET_KEY);
