import { NextResponse } from "next/server";
import PDFDocument from "pdfkit";
import { z } from "zod";
import { writeAuditEvent } from "@/lib/audit/write-event";
import { getProjectRegister, plainValue } from "@/lib/exports/project-register";
import { requireProjectPermission, AccessError } from "@/lib/projects/access";
import { enforceExportRateLimit } from "@/lib/redis/rate-limit";

export const runtime = "nodejs";
const input = z.object({ format: z.enum(["pdf", "csv"]), title: z.string().min(1).max(140), theme: z.enum(["classic", "soft-pop", "midnight", "forest"]).default("classic"), watermark: z.string().max(80).optional(), letterhead: z.string().max(2_800_000).optional(), letterheadName: z.string().max(140).optional() });
const palettes = { classic: { ink: "#17201c", accent: "#245e42", soft: "#eef3ef" }, "soft-pop": { ink: "#24232b", accent: "#7055d9", soft: "#f2ecff" }, midnight: { ink: "#182437", accent: "#326ecf", soft: "#eaf1ff" }, forest: { ink: "#14392c", accent: "#1c7a57", soft: "#e6f4ec" } };
const esc = (value: string) => `"${value.replaceAll('"', '""')}"`;
const cleanName = (value: string) => value.replace(/[^a-z0-9]+/gi, "-").replace(/^-|-$/g, "").toLowerCase() || "project-export";

function csv(register: Awaited<ReturnType<typeof getProjectRegister>>, theme: string, letterheadName?: string) {
  const lines = ["dataset,record,field,value,export_theme,letterhead_name"];
  const append = (dataset: string, record: string, row: Record<string, unknown>) => Object.entries(row).forEach(([field, value]) => lines.push([dataset, record, field, plainValue(value), theme, letterheadName ?? ""].map(esc).join(",")));
  append("Project", "1", register.project); register.sections.forEach((section) => section.rows.forEach((row, index) => append(section.name, String(index + 1), row)));
  return lines.join("\r\n");
}

function pdf(register: Awaited<ReturnType<typeof getProjectRegister>>, title: string, themeName: keyof typeof palettes, watermark?: string, letterhead?: string) {
  const palette = palettes[themeName]; const doc = new PDFDocument({ size: "A4", margin: 44, info: { Title: `${title} - ${plainValue(register.project.name)}`, Author: "Pramana CX", Subject: "Controlled project data export" } }); const chunks: Buffer[] = []; doc.on("data", (chunk) => chunks.push(chunk));
  const footer = () => { const y = doc.page.height - 32; doc.fontSize(7).fillColor("#68736d").text(`Controlled project data export | Generated ${new Date(register.generatedAt).toLocaleString("en-IN")} | Page ${doc.bufferedPageRange().count}`, 44, y, { width: 507, align: "center" }); };
  const heading = (text: string) => { if (doc.y > 710) { footer(); doc.addPage(); } doc.moveDown(.55).fillColor(palette.ink).font("Helvetica-Bold").fontSize(14).text(text); doc.moveDown(.3); };
  doc.on("pageAdded", () => { doc.rect(0, 0, doc.page.width, 7).fill(palette.accent); if (watermark) { doc.save().opacity(.07).fillColor(palette.accent).font("Helvetica-Bold").fontSize(44).rotate(-35, { origin: [290, 430] }).text(watermark.toUpperCase(), 70, 390, { width: 470, align: "center" }).restore(); } });
  doc.rect(0, 0, doc.page.width, 7).fill(palette.accent);
  if (letterhead?.match(/^data:image\/(png|jpe?g);base64,/)) { try { doc.image(Buffer.from(letterhead.split(",")[1], "base64"), 44, 28, { fit: [120, 45] }); } catch {} }
  doc.fillColor(palette.ink).font("Helvetica-Bold").fontSize(22).text(title, 44, 88, { width: 510 }); doc.font("Helvetica").fontSize(10).fillColor("#526058").text(`${plainValue(register.project.name)} | Complete project data register`, 44, 117); doc.moveTo(44, 140).lineTo(551, 140).strokeColor(palette.accent).lineWidth(1).stroke();
  doc.moveDown(4); heading("Document control"); const control = [["Project", plainValue(register.project.name)], ["Generated", new Date(register.generatedAt).toLocaleString("en-IN")], ["Records", String(register.sections.reduce((sum, section) => sum + section.rows.length, 0))], ["Scope", "All project-controlled application records"], ["Theme", themeName], ["Watermark", watermark || "None"]]; control.forEach(([label, value]) => { doc.font("Helvetica-Bold").fontSize(9).fillColor(palette.ink).text(`${label}: `, 44, doc.y, { continued: true }); doc.font("Helvetica").fillColor("#526058").text(value); doc.moveDown(.18); });
  register.sections.forEach((section) => { heading(`${section.name} (${section.rows.length})`); if (!section.rows.length) { doc.font("Helvetica-Oblique").fontSize(9).fillColor("#68736d").text("No records in this project."); return; } const columns = Array.from(new Set(section.rows.flatMap((row) => Object.keys(row)))).filter((key) => !["embedding", "content"].includes(key)).slice(0, 6); const tableY = doc.y; doc.rect(44, tableY, 507, 18).fill(palette.soft); doc.fillColor(palette.ink).font("Helvetica-Bold").fontSize(7); columns.forEach((column, index) => doc.text(column.replace(/([A-Z])/g, " $1").toUpperCase(), 48 + index * (499 / columns.length), tableY + 5, { width: 495 / columns.length - 4, ellipsis: true })); doc.y = tableY + 23; section.rows.forEach((row) => { const line = columns.map((column) => plainValue(row[column]).replace(/\s+/g, " ").slice(0, 120) || "-").join(" | "); const height = Math.max(20, doc.heightOfString(line, { width: 499 })); if (doc.y + height > 748) { footer(); doc.addPage(); } doc.font("Helvetica").fontSize(7.5).fillColor("#29342e").text(line, 48, doc.y, { width: 499, lineGap: 2 }); doc.moveDown(.45); doc.moveTo(44, doc.y).lineTo(551, doc.y).strokeColor("#dce3dd").lineWidth(.5).stroke(); doc.moveDown(.35); }); }); footer(); doc.end(); return new Promise<Buffer>((resolve) => doc.on("end", () => resolve(Buffer.concat(chunks))));
}

export async function POST(request: Request, { params }: { params: Promise<{ projectId: string }> }) { const { projectId } = await params; const parsed = input.safeParse(await request.json().catch(() => null)); if (!parsed.success) return NextResponse.json({ error: "Export settings are invalid." }, { status: 400 }); try { const rate = await enforceExportRateLimit(`project-export:${projectId}`); if (rate) return rate; const actor = await requireProjectPermission(projectId, "audit:view"); const register = await getProjectRegister(projectId); const fileBase = cleanName(`${parsed.data.title}-${plainValue(register.project.name)}`); const body = parsed.data.format === "csv" ? csv(register, parsed.data.theme, parsed.data.letterheadName) : await pdf(register, parsed.data.title, parsed.data.theme, parsed.data.watermark, parsed.data.letterhead); await writeAuditEvent({ projectId, actorId: actor.userId, action: `project_export.${parsed.data.format}`, entityType: "project_export", entityId: projectId, after: { format: parsed.data.format, theme: parsed.data.theme, watermark: Boolean(parsed.data.watermark), letterhead: parsed.data.letterheadName ?? null, sectionCount: register.sections.length } }); return new NextResponse(typeof body === "string" ? body : new Uint8Array(body), { headers: { "content-type": parsed.data.format === "csv" ? "text/csv; charset=utf-8" : "application/pdf", "content-disposition": `attachment; filename=\"${fileBase}.${parsed.data.format}\"` } }); } catch (error) { return NextResponse.json({ error: error instanceof Error ? error.message : "Unable to create export." }, { status: error instanceof AccessError ? error.status : 500 }); } }
