import { desc, eq } from "drizzle-orm";
import { FeatureShell } from "@/components/feature-shell";
import { compactHash } from "@/lib/presentation";
import { TurnoverActions } from "@/components/turnover-actions";
import { getProjectShellData } from "@/lib/dashboard-data";
import { db } from "@/lib/db/client";
import { evidence, gates, turnoverPacks } from "@/lib/db/schema";
import { getActiveProjectId } from "@/lib/projects/current";
export const dynamic = "force-dynamic";
export default async function TurnoverPage() { const projectId = await getActiveProjectId(); const [data, items, gateRows, packs] = await Promise.all([getProjectShellData(projectId), db.select().from(evidence).where(eq(evidence.projectId, projectId)).orderBy(desc(evidence.createdAt)), db.select({ id: gates.id, name: gates.name, status: gates.status }).from(gates).where(eq(gates.projectId, projectId)), db.select().from(turnoverPacks).where(eq(turnoverPacks.projectId, projectId)).orderBy(desc(turnoverPacks.createdAt))]); if (!data) throw new Error("Project not found"); return <FeatureShell projectName={data.project} eyebrow="Assurance · handover controls" title="Turnover & Closeout" description="Only accepted evidence and approved gates can produce a hash-verifiable, signed turnover manifest."><TurnoverActions projectId={projectId} gates={gateRows} /><div className="workflow-stack">{packs.map((pack) => <article className="surface workflow-card" key={pack.id}><span className="source-status processed">verified manifest</span><h2>Turnover pack</h2><p className="mono" title={pack.manifestHash}>{compactHash(pack.manifestHash)}</p></article>)}{items.map((item) => <article className="surface workflow-card" key={item.id}><span className={`source-status ${item.validityState === "accepted" ? "processed" : "pending"}`}>{item.validityState}</span><h2>{item.evidenceType.replaceAll("_", " ")}</h2><p>Captured {new Intl.DateTimeFormat("en-IN", { dateStyle: "medium" }).format(item.capturedAt)}</p><small title={item.contentHash ?? undefined}>Content hash: {compactHash(item.contentHash)}</small></article>)}</div></FeatureShell>; }
