import { and, eq, or } from "drizzle-orm";
import { NextResponse } from "next/server";
import { z } from "zod";
import { writeAuditEvent } from "@/lib/audit/write-event";
import { db } from "@/lib/db/client";
import { scheduleDependencies, scheduleTasks } from "@/lib/db/schema";
import { AccessError, requireProjectPermission } from "@/lib/projects/access";
const schema = z.object({ predecessorTaskId: z.string().uuid(), successorTaskId: z.string().uuid() }).refine((item) => item.predecessorTaskId !== item.successorTaskId);
export async function POST(request: Request, { params }: { params: Promise<{ projectId: string }> }) { const { projectId } = await params; const parsed = schema.safeParse(await request.json().catch(() => null)); if (!parsed.success) return NextResponse.json({ error: "Dependency is invalid." }, { status: 400 }); try { const actor = await requireProjectPermission(projectId, "schedule:manage"); const tasks = await db.select().from(scheduleTasks).where(and(eq(scheduleTasks.projectId, projectId), or(eq(scheduleTasks.id, parsed.data.predecessorTaskId), eq(scheduleTasks.id, parsed.data.successorTaskId)))); if (tasks.length !== 2 || tasks.some((task) => task.reviewState !== "accepted")) return NextResponse.json({ error: "Dependencies require two accepted project tasks." }, { status: 409 }); const [dependency] = await db.insert(scheduleDependencies).values({ projectId, ...parsed.data }).returning(); await writeAuditEvent({ projectId, actorId: actor.userId, action: "schedule.dependency_created", entityType: "schedule_dependency", entityId: dependency.id, after: dependency }); return NextResponse.json({ dependency }, { status: 201 }); } catch (error) { return NextResponse.json({ error: error instanceof Error ? error.message : "Unable to create dependency." }, { status: error instanceof AccessError ? error.status : 409 }); } }
