import { eq } from "drizzle-orm";
import { NextResponse } from "next/server";
import { z } from "zod";
import { writeAuditEvent } from "@/lib/audit/write-event";
import { db } from "@/lib/db/client";
import { documents, documentVersions, projects, storageObjects } from "@/lib/db/schema";
import { enqueueDurableJob } from "@/lib/jobs/queue";
import { AccessError, requireProjectPermission } from "@/lib/projects/access";
import { objectStorage } from "@/lib/storage/service";
const metadata = z.object({ revision: z.string().trim().min(1).max(80) });
export async function POST(request: Request, { params }: { params: Promise<{ documentId: string }> }) { const { documentId } = await params; const document = await db.query.documents.findFirst({ where: eq(documents.id, documentId) }); if (!document) return NextResponse.json({ error: "Document not found." }, { status: 404 }); try { const actor = await requireProjectPermission(document.projectId, "source:upload"); const form = await request.formData(); const parsed = metadata.safeParse({ revision: form.get("revision") }); const file = form.get("file"); if (!parsed.success || !(file instanceof File)) return NextResponse.json({ error: "Revision and PDF are required." }, { status: 400 }); if (file.size < 5 || file.size > 100 * 1024 * 1024) return NextResponse.json({ error: "PDF must be no larger than 100 MB." }, { status: 413 }); const bytes = Buffer.from(await file.arrayBuffer()); if (bytes.subarray(0, 5).toString("ascii") !== "%PDF-") return NextResponse.json({ error: "PDF magic bytes are invalid." }, { status: 415 }); const project = await db.query.projects.findFirst({ where: eq(projects.id, document.projectId) }); if (!project) return NextResponse.json({ error: "Project not found." }, { status: 404 }); const stored = await objectStorage.put({ tenantId: project.tenantId, projectId: project.id, bytes, mediaType: "application/pdf", fileName: file.name || "revision.pdf" }); const duplicate = await db.query.documentVersions.findFirst({ where: eq(documentVersions.sha256, stored.sha256) }); if (duplicate) return NextResponse.json({ error: "This exact source content is already controlled." }, { status: 409 }); const version = await db.transaction(async (tx) => { const [version] = await tx.insert(documentVersions).values({ documentId, revision: parsed.data.revision, sha256: stored.sha256, objectKey: stored.objectKey, mediaType: stored.mediaType, extractionStatus: "processing" }).returning(); await tx.insert(storageObjects).values({ tenantId: project.tenantId, projectId: project.id, objectKey: stored.objectKey, mediaType: stored.mediaType, byteSize: stored.byteSize, sha256: stored.sha256, createdBy: actor.userId }); return version; }); const queued = await enqueueDurableJob({ queue: "core", name: "document.extract", tenantId: project.tenantId, projectId: project.id, idempotencyKey: `document-extract:${version.id}:${stored.sha256}`, payload: { documentVersionId: version.id, objectKey: stored.objectKey } }); await writeAuditEvent({ projectId: project.id, actorId: actor.userId, action: "source.revision_stored", entityType: "document_version", entityId: version.id, after: { documentId, revision: version.revision, sha256: version.sha256, jobId: queued.job.id } }); return NextResponse.json({ version, jobId: queued.job.id, extractionStatus: "processing" }, { status: 202 }); } catch (error) { return NextResponse.json({ error: error instanceof Error ? error.message : "Unable to store revision." }, { status: error instanceof AccessError ? error.status : 500 }); } }
