import { eq } from "drizzle-orm";
import { NextResponse } from "next/server";
import { z } from "zod";
import { writeAuditEvent } from "@/lib/audit/write-event";
import { db } from "@/lib/db/client";
import { scheduleResources } from "@/lib/db/schema";
import { AccessError, requireProjectPermission } from "@/lib/projects/access";
import { enforceScheduleRateLimit } from "@/lib/redis/rate-limit";

const schema = z.object({ name: z.string().trim().min(2).max(200), capacity: z.number().int().positive().max(100000), unit: z.string().trim().min(1).max(60).default("crew"), sourceRegionId: z.string().uuid().optional(), confidence: z.number().min(0).max(1).optional(), validationIssues: z.array(z.string().min(1).max(200)).max(50).default([]) });
export async function GET(_: Request, { params }: { params: Promise<{ projectId: string }> }) { const { projectId } = await params; try { await requireProjectPermission(projectId, "audit:view"); return NextResponse.json({ items: await db.select().from(scheduleResources).where(eq(scheduleResources.projectId, projectId)) }); } catch (error) { return NextResponse.json({ error: error instanceof Error ? error.message : "Unable to load resources." }, { status: error instanceof AccessError ? error.status : 500 }); } }
export async function POST(request: Request, { params }: { params: Promise<{ projectId: string }> }) { const { projectId } = await params; const limited = await enforceScheduleRateLimit(`resources:${projectId}`); if (limited) return limited; const parsed = schema.safeParse(await request.json().catch(() => null)); if (!parsed.success) return NextResponse.json({ error: "Resource proposal is invalid." }, { status: 400 }); try { const actor = await requireProjectPermission(projectId, "schedule:manage"); const [resource] = await db.insert(scheduleResources).values({ projectId, name: parsed.data.name, capacity: parsed.data.capacity, unit: parsed.data.unit, sourceRegionId: parsed.data.sourceRegionId ?? null, confidence: parsed.data.confidence === undefined ? null : String(parsed.data.confidence), validationIssues: parsed.data.validationIssues, reviewState: "proposed" }).returning(); await writeAuditEvent({ projectId, actorId: actor.userId, action: "schedule.resource_proposed", entityType: "schedule_resource", entityId: resource.id, after: resource }); return NextResponse.json({ resource, authority: "proposed" }, { status: 201 }); } catch (error) { return NextResponse.json({ error: error instanceof Error ? error.message : "Unable to create resource proposal." }, { status: error instanceof AccessError ? error.status : 409 }); } }
