import { desc, eq } from "drizzle-orm";
import { NextResponse } from "next/server";
import { z } from "zod";
import { writeAuditEvent } from "@/lib/audit/write-event";
import { db } from "@/lib/db/client";
import { technologyPluginDrafts } from "@/lib/db/schema";
import { AccessError, requireProjectPermission } from "@/lib/projects/access";

const schema = z.object({ templateId: z.string().min(2).max(120), category: z.string().min(2).max(80), solutionName: z.string().trim().min(3).max(200), summary: z.string().trim().min(20).max(5000), evidenceChecklist: z.array(z.string().min(2).max(240)).min(1).max(20), claims: z.array(z.object({ type: z.string().min(2).max(100), text: z.string().min(8).max(1000), evidenceRequired: z.string().min(2).max(500) })).min(1).max(10), parameters: z.array(z.object({ key: z.string().min(2).max(100), label: z.string().min(2).max(200), unit: z.string().min(1).max(60), sourceHint: z.string().min(2).max(500) })).min(1).max(20), commercialChecklist: z.array(z.string().min(2).max(240)).min(1).max(20) });
export async function GET(_: Request, { params }: { params: Promise<{ projectId: string }> }) { const { projectId } = await params; try { await requireProjectPermission(projectId, "audit:view"); return NextResponse.json({ drafts: await db.select().from(technologyPluginDrafts).where(eq(technologyPluginDrafts.projectId, projectId)).orderBy(desc(technologyPluginDrafts.updatedAt)) }); } catch (error) { return NextResponse.json({ error: error instanceof Error ? error.message : "Unable to load technology drafts." }, { status: error instanceof AccessError ? error.status : 500 }); } }
export async function POST(request: Request, { params }: { params: Promise<{ projectId: string }> }) { const { projectId } = await params; const parsed = schema.safeParse(await request.json().catch(() => null)); if (!parsed.success) return NextResponse.json({ error: "Technology draft is invalid.", issues: parsed.error.flatten() }, { status: 400 }); try { const actor = await requireProjectPermission(projectId, "configuration:manage"); const [draft] = await db.insert(technologyPluginDrafts).values({ projectId, ...parsed.data, status: "draft" }).returning(); await writeAuditEvent({ projectId, actorId: actor.userId, action: "technology_draft.created", entityType: "technology_draft", entityId: draft.id, after: { templateId: draft.templateId, category: draft.category, status: "draft", publishable: false } }); return NextResponse.json({ draft }, { status: 201 }); } catch (error) { return NextResponse.json({ error: error instanceof Error ? error.message : "Unable to save technology draft." }, { status: error instanceof AccessError ? error.status : 500 }); } }
