import PDFDocument from "pdfkit";
import type { RackModelBundle } from "@/lib/rack-model/types";

function yamlString(value: unknown) {
  return JSON.stringify(String(value ?? ""));
}

function safeId(value: string) {
  return (
    value
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/^-|-$/g, "") || "item"
  );
}

function equipmentGroup(type: string) {
  if (type === "network") return "network";
  if (type === "storage") return "storage";
  return "nodes";
}

export function createRackDbYaml(bundle: RackModelBundle) {
  const rows = new Map<string, RackModelBundle["racks"]>();
  for (const rack of bundle.racks)
    rows.set(rack.rowLabel, [...(rows.get(rack.rowLabel) ?? []), rack]);
  const equipmentTypes = new Map<
    string,
    { group: string; height: number; model: string }
  >();
  for (const item of bundle.equipment) {
    const id = `${safeId(item.equipmentType)}-${item.unitHeight}u`;
    equipmentTypes.set(id, {
      group: equipmentGroup(item.equipmentType),
      height: item.unitHeight,
      model: item.modelReference || item.equipmentType,
    });
  }
  const rack = bundle.racks[0];
  const maxX = Math.max(
    ...bundle.racks.map((item) => item.xMm + item.widthMm),
    4000,
  );
  const maxY = Math.max(
    ...bundle.racks.map((item) => item.yMm + item.depthMm),
    4000,
  );
  const location = ((bundle.model.basis ?? {}) as Record<string, unknown>)
    .location;
  const lines = [
    "# RackDB-compatible planning database generated by Pramana Cx",
    `# Model ${bundle.model.id} revision ${bundle.model.revision}; status: ${bundle.model.status}`,
    `# Source hash: ${bundle.model.sourceHash}`,
    "types:",
    "  racks:",
    "  - id: pramana-planning-rack",
    `    height: ${rack?.heightMm ?? 2200}mm`,
    `    width: ${rack?.widthMm ?? 600}mm`,
    `    depth: ${rack?.depthMm ?? 1200}mm`,
    `    slots: ${rack?.totalUnits ?? 48}u`,
  ];
  for (const group of ["nodes", "network", "storage"]) {
    const items = [...equipmentTypes].filter(
      ([, item]) => item.group === group,
    );
    if (!items.length) continue;
    lines.push(`  ${group}:`);
    for (const [id, item] of items) {
      lines.push(
        `  - id: ${id}`,
        `    model: ${yamlString(item.model)}`,
        `    height: ${item.height}u`,
        "    width: full",
      );
    }
  }
  lines.push(
    "",
    "datacenters:",
    `- name: ${safeId(bundle.model.name)}`,
    `  tags: [pramana, planning, ${safeId(bundle.model.status)}]`,
    "  rooms:",
    "  - name: primary-hall",
    "    dimensions:",
    `      depth: ${Math.ceil((maxY + 1500) / 1000)}m`,
    `      width: ${Math.ceil((maxX + 1500) / 1000)}m`,
    "    rows:",
  );
  for (const [rowLabel, rowRacks] of rows) {
    const first = rowRacks.sort((a, b) => a.positionIndex - b.positionIndex)[0];
    lines.push(
      `    - name: ${rowLabel}`,
      ...(Number(rowLabel.charCodeAt(0)) % 2 ? ["      reversed: true"] : []),
      "      position:",
      `        depth: ${(first.yMm / 1000 + 1).toFixed(2)}m`,
      `        width: ${(first.xMm / 1000 + 1).toFixed(2)}m`,
      "      racks:",
    );
    for (const item of rowRacks)
      lines.push(
        `      - name: ${item.name}`,
        "        type: pramana-planning-rack",
      );
  }
  if (location)
    lines.push(`  # Project location: ${String(location).replace(/\n/g, " ")}`);
  if (bundle.clusters.length) {
    lines.push("", "gpu_clusters:");
    for (const cluster of bundle.clusters) {
      const profile = bundle.gpuProfiles.find(
        (item) => item.clusterId === cluster.id,
      );
      lines.push(
        `- name: ${yamlString(cluster.name)}`,
        `  workload: ${yamlString(cluster.workload)}`,
        `  topology: ${yamlString(cluster.topology)}`,
        `  fabric: ${yamlString(cluster.networkFabric)}`,
        `  gpu_vendor: ${yamlString(profile?.vendor)}`,
        `  gpu_model: ${yamlString(profile?.model)}`,
        `  gpus_per_node: ${profile?.gpusPerNode ?? 0}`,
        `  nodes_per_rack: ${profile?.nodesPerRack ?? 0}`,
        `  planned_links: ${bundle.links.filter((link) => link.clusterId === cluster.id).length}`,
      );
    }
  }
  lines.push(
    "",
    "infrastructures:",
    `- name: ${safeId(bundle.model.name)}-infrastructure`,
    `  description: ${yamlString(bundle.model.name)}`,
    "  tags: [pramana, generated, planning]",
    "  layout:",
  );
  for (const rackRow of bundle.racks) {
    lines.push(`  - rack: ${rackRow.name}`);
    const rackEquipment = bundle.equipment.filter(
      (item) => item.rackId === rackRow.id,
    );
    const grouped = new Map<string, typeof rackEquipment>();
    for (const item of rackEquipment) {
      const group = equipmentGroup(item.equipmentType);
      grouped.set(group, [...(grouped.get(group) ?? []), item]);
    }
    for (const [group, items] of grouped) {
      lines.push(`    ${group}:`);
      for (const item of items) {
        lines.push(
          `    - name: ${safeId(item.name)}`,
          `      type: ${safeId(item.equipmentType)}-${item.unitHeight}u`,
          `      slot: ${item.startUnit}`,
          `      tags: [${item.sourceAssetId ? "controlled-asset" : "planning-envelope"}]`,
        );
      }
    }
  }
  return Buffer.from(`${lines.join("\n")}\n`, "utf8");
}

function addBoxObj(
  lines: string[],
  name: string,
  x: number,
  y: number,
  z: number,
  w: number,
  d: number,
  h: number,
  vertexOffset: number,
) {
  lines.push(`o ${safeId(name)}`);
  const points = [
    [x, y, z],
    [x + w, y, z],
    [x + w, y + d, z],
    [x, y + d, z],
    [x, y, z + h],
    [x + w, y, z + h],
    [x + w, y + d, z + h],
    [x, y + d, z + h],
  ];
  for (const point of points)
    lines.push(
      `v ${point[0].toFixed(4)} ${point[2].toFixed(4)} ${point[1].toFixed(4)}`,
    );
  const f = (a: number, b: number, c: number, d0: number) =>
    lines.push(
      `f ${a + vertexOffset} ${b + vertexOffset} ${c + vertexOffset} ${d0 + vertexOffset}`,
    );
  f(1, 2, 3, 4);
  f(5, 8, 7, 6);
  f(1, 5, 6, 2);
  f(2, 6, 7, 3);
  f(3, 7, 8, 4);
  f(5, 1, 4, 8);
}

export function createObj(bundle: RackModelBundle) {
  const lines = [
    "# Pramana Cx rack planning model",
    `# source-hash ${bundle.model.sourceHash}`,
  ];
  let vertexOffset = 0;
  for (const rack of bundle.racks) {
    addBoxObj(
      lines,
      rack.name,
      rack.xMm / 1000,
      rack.yMm / 1000,
      rack.zMm / 1000,
      rack.widthMm / 1000,
      rack.depthMm / 1000,
      rack.heightMm / 1000,
      vertexOffset,
    );
    vertexOffset += 8;
    const unitHeight = rack.heightMm / rack.totalUnits;
    for (const item of bundle.equipment.filter(
      (equipment) => equipment.rackId === rack.id,
    )) {
      const itemHeight = unitHeight * item.unitHeight;
      addBoxObj(
        lines,
        `${rack.name}-${item.name}`,
        (rack.xMm + rack.widthMm * 0.07) / 1000,
        (rack.yMm + rack.depthMm * 0.09) / 1000,
        (rack.zMm + unitHeight * (item.startUnit - 1)) / 1000,
        (rack.widthMm * 0.86) / 1000,
        (rack.depthMm * 0.82) / 1000,
        itemHeight / 1000,
        vertexOffset,
      );
      vertexOffset += 8;
    }
  }
  return Buffer.from(`${lines.join("\n")}\n`, "utf8");
}

function pad4(buffer: Buffer, byte = 0) {
  const padding = (4 - (buffer.length % 4)) % 4;
  return padding
    ? Buffer.concat([buffer, Buffer.alloc(padding, byte)])
    : buffer;
}

export function createGlb(bundle: RackModelBundle) {
  const positionValues = new Float32Array([
    -0.5, -0.5, -0.5, 0.5, -0.5, -0.5, 0.5, 0.5, -0.5, -0.5, 0.5, -0.5, -0.5,
    -0.5, 0.5, 0.5, -0.5, 0.5, 0.5, 0.5, 0.5, -0.5, 0.5, 0.5,
  ]);
  const indexValues = new Uint16Array([
    0, 2, 1, 0, 3, 2, 4, 5, 6, 4, 6, 7, 0, 1, 5, 0, 5, 4, 1, 2, 6, 1, 6, 5, 2,
    3, 7, 2, 7, 6, 3, 0, 4, 3, 4, 7,
  ]);
  const positions = Buffer.from(positionValues.buffer);
  const indices = Buffer.from(indexValues.buffer);
  const bin = pad4(Buffer.concat([positions, indices]));
  const materialDefinitions = [
    ["Rack planning shell", [0.12, 0.38, 0.32, 0.45]],
    ["Compute nodes", [0.91, 0.7, 0.36, 1]],
    ["Network", [0.49, 0.72, 0.91, 1]],
    ["Storage", [0.66, 0.55, 0.87, 1]],
    ["Power", [0.88, 0.42, 0.4, 1]],
    ["Cooling", [0.39, 0.78, 0.74, 1]],
  ] as const;
  const materialIndex: Record<string, number> = {
    rack: 0,
    nodes: 1,
    network: 2,
    storage: 3,
    power: 4,
    cooling: 5,
  };
  const rackNodes = bundle.racks.map((rack) => ({
    name: rack.name,
    mesh: 0,
    translation: [
      (rack.xMm + rack.widthMm / 2) / 1000,
      (rack.zMm + rack.heightMm / 2) / 1000,
      (rack.yMm + rack.depthMm / 2) / 1000,
    ],
    scale: [rack.widthMm / 1000, rack.heightMm / 1000, rack.depthMm / 1000],
    extras: {
      rackId: rack.id,
      row: rack.rowLabel,
      maxPowerKw: rack.maxPowerKw,
      sourceHash: bundle.model.sourceHash,
    },
  }));
  const rackById = new Map(bundle.racks.map((rack) => [rack.id, rack]));
  const equipmentNodes = bundle.equipment.flatMap((item) => {
    const rack = rackById.get(item.rackId);
    if (!rack) return [];
    const unitHeightMm = rack.heightMm / rack.totalUnits;
    const itemHeightMm = unitHeightMm * item.unitHeight;
    return [
      {
        name: `${rack.name} / ${item.name}`,
        mesh: materialIndex[item.equipmentType] ?? materialIndex.nodes,
        translation: [
          (rack.xMm + rack.widthMm / 2) / 1000,
          (rack.zMm + unitHeightMm * (item.startUnit - 1) + itemHeightMm / 2) /
            1000,
          (rack.yMm + rack.depthMm / 2) / 1000,
        ],
        scale: [
          (rack.widthMm * 0.86) / 1000,
          Math.max(itemHeightMm - 8, 8) / 1000,
          (rack.depthMm * 0.82) / 1000,
        ],
        extras: {
          rackId: rack.id,
          equipmentId: item.id,
          equipmentType: item.equipmentType,
          sourceAssetId: item.sourceAssetId,
          clusterId: item.clusterId,
          gpuProfileId: item.gpuProfileId,
          acceleratorCount: item.acceleratorCount,
          provenance: item.provenance,
        },
      },
    ];
  });
  const nodes = [...rackNodes, ...equipmentNodes];
  const gltf = {
    asset: { version: "2.0", generator: "Pramana Cx RackDB-first modeler" },
    extras: {
      rackModelId: bundle.model.id,
      gpuClusters: bundle.clusters,
      gpuProfiles: bundle.gpuProfiles,
      fabricPorts: bundle.ports,
      fabricLinks: bundle.links,
    },
    scene: 0,
    scenes: [{ nodes: nodes.map((_, index) => index) }],
    nodes,
    meshes: materialDefinitions.map((_, index) => ({
      primitives: [
        { attributes: { POSITION: 0 }, indices: 1, material: index },
      ],
    })),
    materials: materialDefinitions.map(([name, baseColorFactor], index) => ({
      name,
      alphaMode: index === 0 ? "BLEND" : "OPAQUE",
      pbrMetallicRoughness: {
        baseColorFactor,
        metallicFactor: index === 0 ? 0.15 : 0.04,
        roughnessFactor: 0.7,
      },
    })),
    buffers: [{ byteLength: bin.length }],
    bufferViews: [
      { buffer: 0, byteOffset: 0, byteLength: positions.length, target: 34962 },
      {
        buffer: 0,
        byteOffset: positions.length,
        byteLength: indices.length,
        target: 34963,
      },
    ],
    accessors: [
      {
        bufferView: 0,
        componentType: 5126,
        count: 8,
        type: "VEC3",
        min: [-0.5, -0.5, -0.5],
        max: [0.5, 0.5, 0.5],
      },
      {
        bufferView: 1,
        componentType: 5123,
        count: 36,
        type: "SCALAR",
        min: [0],
        max: [7],
      },
    ],
  };
  const json = pad4(Buffer.from(JSON.stringify(gltf), "utf8"), 0x20);
  const header = Buffer.alloc(12);
  header.writeUInt32LE(0x46546c67, 0);
  header.writeUInt32LE(2, 4);
  header.writeUInt32LE(12 + 8 + json.length + 8 + bin.length, 8);
  const jsonHeader = Buffer.alloc(8);
  jsonHeader.writeUInt32LE(json.length, 0);
  jsonHeader.writeUInt32LE(0x4e4f534a, 4);
  const binHeader = Buffer.alloc(8);
  binHeader.writeUInt32LE(bin.length, 0);
  binHeader.writeUInt32LE(0x004e4942, 4);
  return Buffer.concat([header, jsonHeader, json, binHeader, bin]);
}

function text(
  doc: PDFKit.PDFDocument,
  value: string,
  options: PDFKit.Mixins.TextOptions = {},
) {
  doc
    .fillColor("#26322f")
    .font("Helvetica")
    .fontSize(9)
    .text(pdfSafe(value), options);
}

function pdfSafe(value: unknown) {
  return String(value ?? "").replace(/[^\x20-\x7E]/g, "-");
}

export async function createRackModelPdf(bundle: RackModelBundle) {
  const summary = (bundle.model.summary ?? {}) as Record<string, unknown>;
  const basis = (bundle.model.basis ?? {}) as Record<string, unknown>;
  const chunks: Buffer[] = [];
  const doc = new PDFDocument({
    bufferPages: true,
    size: "A4",
    margins: { top: 46, bottom: 48, left: 48, right: 48 },
    info: { Title: pdfSafe(bundle.model.name), Author: "Pramana Cx" },
  });
  doc.on("data", (chunk) => chunks.push(Buffer.from(chunk)));
  const done = new Promise<Buffer>((resolve, reject) => {
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);
  });
  const pageWidth = doc.page.width - 96;
  doc
    .fillColor("#123c34")
    .font("Helvetica-Bold")
    .fontSize(10)
    .text("PRAMANA.CX  /  DIGITAL RACK MODEL");
  doc.moveDown(0.8).fontSize(24).text(pdfSafe(bundle.model.name));
  doc
    .moveDown(0.3)
    .fillColor("#5b6864")
    .font("Helvetica")
    .fontSize(9)
    .text(
      `Revision ${bundle.model.revision}  |  ${bundle.model.status.toUpperCase()}  |  Generated ${new Date(bundle.model.createdAt ?? Date.now()).toLocaleString("en-GB")}`,
    );
  doc.moveDown(1.2);
  const metrics = [
    ["Racks", String(summary.rackCount ?? bundle.racks.length)],
    [
      "Rows",
      String(
        summary.rowCount ??
          new Set(bundle.racks.map((item) => item.rowLabel)).size,
      ),
    ],
    [
      "Planned IT",
      summary.plannedItMw
        ? `${Number(summary.plannedItMw).toFixed(2)} MW`
        : "Unresolved",
    ],
    [
      "GPUs / links",
      `${summary.plannedGpuCount ?? 0} / ${bundle.links.length}`,
    ],
  ];
  const metricWidth = pageWidth / metrics.length;
  const metricY = doc.y;
  metrics.forEach(([label, value], index) => {
    const x = 48 + index * metricWidth;
    doc
      .roundedRect(x, metricY, metricWidth - 8, 52, 6)
      .fillAndStroke("#eef5f2", "#c6d5d0");
    doc
      .fillColor("#60706b")
      .font("Helvetica")
      .fontSize(7)
      .text(label.toUpperCase(), x + 10, metricY + 10, {
        width: metricWidth - 28,
      });
    doc
      .fillColor("#123c34")
      .font("Helvetica-Bold")
      .fontSize(15)
      .text(pdfSafe(value), x + 10, metricY + 24, { width: metricWidth - 28 });
  });
  doc.x = 48;
  doc.y = metricY + 68;
  doc
    .fillColor("#26322f")
    .font("Helvetica-Bold")
    .fontSize(13)
    .text("Planning basis");
  doc.moveDown(0.5);
  const basisRows = [
    ["Location", basis.location],
    ["Platform", basis.platform],
    ["Workload", basis.workload],
    ["Cooling", basis.coolingArchitecture],
    ["Layout", basis.buildingLayout],
  ];
  for (const [label, value] of basisRows) {
    doc.x = 48;
    doc
      .fillColor("#60706b")
      .font("Helvetica-Bold")
      .fontSize(8)
      .text(`${label}:`, { continued: true });
    doc
      .fillColor("#26322f")
      .font("Helvetica")
      .text(` ${pdfSafe(value || "Unresolved")}`);
  }
  doc.moveDown(1);
  doc.x = 48;
  doc
    .fillColor("#26322f")
    .font("Helvetica-Bold")
    .fontSize(13)
    .text("Top view - planning geometry");
  const viewX = 48,
    viewY = doc.y + 8,
    viewW = pageWidth,
    viewH = 190;
  doc
    .roundedRect(viewX, viewY, viewW, viewH, 6)
    .fillAndStroke("#f8faf9", "#cbd6d2");
  const maxX = Math.max(
    ...bundle.racks.map((item) => item.xMm + item.widthMm),
    1,
  );
  const maxY = Math.max(
    ...bundle.racks.map((item) => item.yMm + item.depthMm),
    1,
  );
  const scale = Math.min(
    (viewW - 30) / Math.max(maxX, 1),
    (viewH - 30) / Math.max(maxY, 1),
  );
  const originX = viewX + (viewW - maxX * scale) / 2;
  const originY = viewY + (viewH - maxY * scale) / 2;
  for (const rack of bundle.racks) {
    const x = originX + rack.xMm * scale,
      y = originY + rack.yMm * scale;
    doc
      .rect(
        x,
        y,
        Math.max(2, rack.widthMm * scale),
        Math.max(4, rack.depthMm * scale),
      )
      .fillAndStroke("#2d6f61", "#17483f");
  }
  doc.x = 48;
  doc.y = viewY + viewH + 16;
  doc
    .fillColor("#26322f")
    .font("Helvetica-Bold")
    .fontSize(13)
    .text("Assumptions and review limitations");
  doc.moveDown(0.5);
  const assumptions = Array.isArray(basis.assumptions) ? basis.assumptions : [];
  for (const item of assumptions) text(doc, `- ${String(item)}`, { indent: 8 });
  text(
    doc,
    "This model is a planning artifact. It does not constitute a coordinated construction model, OEM approval, structural verification, or issued-for-construction rack elevation.",
  );
  if (bundle.clusters.length) {
    doc.moveDown(1);
    doc.x = 48;
    doc
      .fillColor("#26322f")
      .font("Helvetica-Bold")
      .fontSize(13)
      .text("GPU cluster and fabric schedule");
    doc.moveDown(0.5);
    for (const cluster of bundle.clusters) {
      const profile = bundle.gpuProfiles.find(
        (item) => item.clusterId === cluster.id,
      );
      text(
        doc,
        `${cluster.name}: ${profile?.vendor ?? "-"} ${profile?.model ?? "-"}; ${profile?.gpusPerNode ?? 0} GPUs/node; ${profile?.nodesPerRack ?? 0} nodes/rack; ${cluster.networkFabric ?? "fabric unresolved"}; ${bundle.links.filter((link) => link.clusterId === cluster.id).length} persisted links.`,
      );
    }
  }
  doc.addPage();
  doc
    .fillColor("#123c34")
    .font("Helvetica-Bold")
    .fontSize(16)
    .text("Representative rack elevation");
  doc
    .moveDown(0.25)
    .fillColor("#60706b")
    .font("Helvetica")
    .fontSize(8.5)
    .text(
      "Front elevation of the rack with the greatest number of mapped records. Colors identify equipment classes; labels preserve source status.",
    );
  const representative = [...bundle.racks].sort(
    (left, right) =>
      bundle.equipment.filter((item) => item.rackId === right.id).length -
      bundle.equipment.filter((item) => item.rackId === left.id).length,
  )[0];
  if (representative) {
    const elevation = bundle.equipment.filter(
      (item) => item.rackId === representative.id,
    );
    const rackX = 72,
      rackY = 118,
      rackW = 165,
      rackH = 590;
    doc
      .roundedRect(rackX, rackY, rackW, rackH, 5)
      .fillAndStroke("#eef5f2", "#123c34");
    const colors: Record<string, string> = {
      nodes: "#e8b35d",
      network: "#7cb8e8",
      storage: "#a98bdd",
      power: "#e16b67",
      cooling: "#63c7bd",
    };
    for (let unit = 1; unit < representative.totalUnits; unit += 1) {
      const lineY = rackY + rackH - (unit * rackH) / representative.totalUnits;
      doc
        .moveTo(rackX, lineY)
        .lineTo(rackX + rackW, lineY)
        .strokeColor("#d5dfdb")
        .lineWidth(0.25)
        .stroke();
    }
    elevation.forEach((item, index) => {
      const unitH = rackH / representative.totalUnits;
      const y = rackY + rackH - (item.startUnit - 1 + item.unitHeight) * unitH;
      const h = Math.max(item.unitHeight * unitH, 2);
      doc
        .rect(rackX + 7, y, rackW - 14, h)
        .fillAndStroke(colors[item.equipmentType] ?? colors.nodes, "#ffffff");
      const labelY = 128 + index * 48;
      doc
        .fillColor("#123c34")
        .font("Helvetica-Bold")
        .fontSize(8)
        .text(pdfSafe(item.name), 270, labelY, { width: 250, ellipsis: true });
      doc
        .fillColor("#60706b")
        .font("Helvetica")
        .fontSize(7.5)
        .text(
          `U${item.startUnit}-U${item.startUnit + item.unitHeight - 1} | ${pdfSafe(item.equipmentType)} | ${item.sourceAssetId ? "controlled asset" : "planning envelope"}`,
          270,
          labelY + 14,
          { width: 250 },
        );
    });
    doc
      .fillColor("#123c34")
      .font("Helvetica-Bold")
      .fontSize(10)
      .text(
        `${representative.name} | ${representative.totalUnits}U | ${representative.maxPowerKw ?? "-"} kW basis`,
        72,
        728,
        { width: 450 },
      );
  }
  doc.addPage();
  const headers = ["Rack", "Row", "Position", "Power kW", "Mapped items"];
  const widths = [92, 55, 66, 70, 216];
  const equipmentCounts = new Map<string, number>();
  for (const item of bundle.equipment) {
    equipmentCounts.set(
      item.rackId,
      (equipmentCounts.get(item.rackId) ?? 0) + 1,
    );
  }
  let y = 48;
  const drawTableRow = (values: string[], header = false) => {
    let x = 48;
    values.forEach((value, index) => {
      doc
        .rect(x, y, widths[index], 22)
        .fillAndStroke(
          header
            ? "#123c34"
            : Math.floor((y - 48) / 22) % 2
              ? "#f5f8f7"
              : "#ffffff",
          "#d7dfdc",
        );
      doc
        .fillColor(header ? "#ffffff" : "#26322f")
        .font(header ? "Helvetica-Bold" : "Helvetica")
        .fontSize(7.5)
        .text(pdfSafe(value), x + 5, y + 7, {
          width: widths[index] - 10,
          ellipsis: true,
          lineBreak: false,
        });
      x += widths[index];
    });
    y += 22;
  };
  const drawSchedulePageHeader = (continued = false) => {
    doc
      .fillColor("#123c34")
      .font("Helvetica-Bold")
      .fontSize(16)
      .text(continued ? "Rack schedule - continued" : "Rack schedule", 48, 48, {
        width: pageWidth,
      });
    y = 78;
    drawTableRow(headers, true);
  };
  drawSchedulePageHeader();
  for (const rack of bundle.racks) {
    // Break before PDFKit's own bottom-margin guard can create an unheaded
    // continuation page while writing the final cell of a row.
    if (y + 22 > doc.page.height - doc.page.margins.bottom) {
      doc.addPage();
      drawSchedulePageHeader(true);
    }
    drawTableRow([
      rack.name,
      rack.rowLabel,
      String(rack.positionIndex + 1),
      rack.maxPowerKw ?? "-",
      String(equipmentCounts.get(rack.id) ?? 0),
    ]);
  }
  const pages = doc.bufferedPageRange();
  for (let page = 0; page < pages.count; page += 1) {
    doc.switchToPage(page);
    doc.page.margins.bottom = 0;
    doc
      .font("Helvetica")
      .fontSize(7)
      .fillColor("#66736f")
      .text(
        `Source hash: ${bundle.model.sourceHash.slice(0, 16)}...   |   Page ${page + 1} of ${pages.count}`,
        48,
        doc.page.height - 34,
        { width: pageWidth, align: "center", lineBreak: false },
      );
  }
  doc.end();
  return done;
}
