import { createHash } from "node:crypto";
import { and, desc, eq, inArray, sql } from "drizzle-orm";
import { db } from "@/lib/db/client";
import { scheduleAssignments, scheduleDependencies, scheduleResources, scheduleTaskResources, scheduleTasks, scheduleVersions } from "@/lib/db/schema";
import { writeAuditEvent } from "@/lib/audit/write-event";
import { getModelProvider } from "@/lib/model/provider";
import { assertAcyclic, solveSchedule, type SolverInput } from "@/lib/schedule/solver";
import { z } from "zod";
const explanationSchema = z.object({ explanation: z.string().min(10).max(2000) });
const hash = (value: unknown) => createHash("sha256").update(JSON.stringify(value)).digest("hex");

export async function createScheduleVersion(input: { projectId: string; actorId: string; horizonStart: Date; reason: string }) {
  const tasks = await db.select().from(scheduleTasks).where(and(eq(scheduleTasks.projectId, input.projectId), eq(scheduleTasks.reviewState, "accepted"))); if (!tasks.length) throw new Error("At least one accepted task is required.");
  const taskIds = tasks.map((item) => item.id); const [dependencies, resources, demands, parent] = await Promise.all([db.select().from(scheduleDependencies).where(eq(scheduleDependencies.projectId, input.projectId)), db.select().from(scheduleResources).where(eq(scheduleResources.projectId, input.projectId)), db.select().from(scheduleTaskResources).where(inArray(scheduleTaskResources.taskId, taskIds)), db.query.scheduleVersions.findFirst({ where: eq(scheduleVersions.projectId, input.projectId), orderBy: [desc(scheduleVersions.versionNumber)] })]); assertAcyclic(taskIds, dependencies);
  const previousAssignments = parent ? await db.select().from(scheduleAssignments).where(eq(scheduleAssignments.versionId, parent.id)) : [];
  const offset = (date: Date | null, mode: "ceil" | "floor") => date ? Math.max(0, Math[mode]((date.getTime() - input.horizonStart.getTime()) / 3_600_000)) : null;
  const constraints = { tasks: tasks.map((task) => ({ id: task.id, duration_hours: task.durationHours, earliest_offset: offset(task.earliestStart, "ceil") ?? 0, deadline_offset: offset(task.deadline, "floor"), fixed_offset: offset(task.fixedStart, "ceil") })), dependencies: dependencies.map((item) => ({ predecessor_id: item.predecessorTaskId, successor_id: item.successorTaskId })), resources: resources.map((item) => ({ id: item.id, capacity: item.capacity })), demands: demands.map((item) => ({ task_id: item.taskId, resource_id: item.resourceId, demand: item.demand })) };
  const solverInput: SolverInput = { ...constraints, hints: previousAssignments.filter((item) => taskIds.includes(item.taskId)).map((item) => ({ task_id: item.taskId, start_offset: Math.max(0, Math.round((item.startAt.getTime() - input.horizonStart.getTime()) / 3_600_000)) })) };
  const inputHash = hash(constraints); const solved = await solveSchedule(solverInput);
  const version = await db.transaction(async (tx) => { await tx.execute(sql`select pg_advisory_xact_lock(hashtext(${`schedule:${input.projectId}`}))`); const [latest] = await tx.select().from(scheduleVersions).where(eq(scheduleVersions.projectId, input.projectId)).orderBy(desc(scheduleVersions.versionNumber)).limit(1); const [version] = await tx.insert(scheduleVersions).values({ projectId: input.projectId, parentVersionId: latest?.id ?? null, versionNumber: (latest?.versionNumber ?? 0) + 1, reason: input.reason, solverStatus: solved.status, inputHash, objectiveHours: solved.objective_hours, criticalTaskIds: solved.critical_task_ids, createdBy: input.actorId }).returning(); if (solved.assignments.length) await tx.insert(scheduleAssignments).values(solved.assignments.map((item) => ({ versionId: version.id, taskId: item.task_id, startAt: new Date(input.horizonStart.getTime() + item.start_offset * 3_600_000), endAt: new Date(input.horizonStart.getTime() + item.end_offset * 3_600_000), isCritical: solved.critical_task_ids.includes(item.task_id) }))); return version; });
  await writeAuditEvent({ projectId: input.projectId, actorId: input.actorId, action: "schedule.version_saved", entityType: "schedule_version", entityId: version.id, after: { versionNumber: version.versionNumber, solverStatus: solved.status, inputHash, objectiveHours: solved.objective_hours, warmStartHints: solverInput.hints?.length ?? 0 } });
  const taskNames = new Map(tasks.map((task) => [task.id, task.name])); const mock = { explanation: solved.status === "INFEASIBLE" ? `Version ${version.versionNumber} is infeasible: ${solved.bottlenecks.join(" ")}` : `Version ${version.versionNumber} schedules ${tasks.length} accepted task${tasks.length === 1 ? "" : "s"} over ${solved.objective_hours} hours. Critical completion is driven by ${solved.critical_task_ids.map((id) => taskNames.get(id) ?? id).join(", ") || "the solved terminal path"}.` };
  const generated = await getModelProvider().generateStructured({ system: "Explain a saved deterministic schedule without changing dates or claiming authority.", prompt: JSON.stringify({ version: version.versionNumber, reason: input.reason, solver: solved }), schema: explanationSchema, mock }); await db.update(scheduleVersions).set({ explanation: generated.data.explanation, updatedAt: new Date() }).where(eq(scheduleVersions.id, version.id));
  return { version: { ...version, explanation: generated.data.explanation }, solver: solved, explanationProvider: generated.provider, warmStartHintCount: solverInput.hints?.length ?? 0 };
}
