import { z } from "zod";
import { callProjectRoute } from "@/lib/copilot/invoke";
import type { CopilotTool } from "@/lib/copilot/types";
const coordinate = z.object({ name: z.string().trim().min(2).max(200), lat: z.number().min(-90).max(90), lng: z.number().min(-180).max(180) });
const createShipment = z.object({ name: z.string().min(3).max(200), equipmentId: z.string().uuid(), planId: z.string().uuid().optional(), transportMode: z.enum(["sea", "air", "land"]).default("sea"), origin: coordinate, destination: coordinate, mmsi: z.string().regex(/^\d{7,9}$/).optional(), plannedEta: z.string().datetime(), requiredOnSite: z.string().datetime(), portCongestion: z.boolean().default(false), weatherDelayFactor: z.number().min(0).max(2).default(0) });
const updateShipment = z.object({ shipmentId: z.string().uuid(), plannedEta: z.string().datetime().optional(), requiredOnSite: z.string().datetime().optional(), portCongestion: z.boolean().optional(), weatherDelayFactor: z.coerce.number().min(0).optional(), status: z.enum(["green", "amber", "red", "delivered"]).optional(), currentPosition: z.object({ lat: z.number().min(-90).max(90), lng: z.number().min(-180).max(180), source: z.enum(["live", "simulated"]), reason: z.string().trim().max(1000).optional() }).optional(), assessedThreats: z.array(z.string()).optional() });
const planAction = z.object({ action: z.enum(["generate", "approve", "reject", "materialize"]), planId: z.string().uuid().optional() });
export const tools: CopilotTool[] = [
  { name: "shipments.create", description: "Register a simulated shipment and report its computed status.", permission: "schedule:manage", mutating: true, input: createShipment, transport: { kind: "http", method: "POST", path: (a) => `/api/projects/${a.projectId}/shipments` }, async execute(ctx, args) { return callProjectRoute(ctx, "POST", (a) => `/api/projects/${a.projectId}/shipments`, args, "shipmentDetail"); } },
  { name: "shipments.bulk_import", description: "Import a CSV shipment attachment; rows are project-scoped and invalid equipment rows are skipped.", permission: "schedule:manage", rateLimit: "schedule", mutating: true, input: z.object({ attachmentId: z.string().uuid() }), transport: { kind: "http", method: "POST", path: (a) => `/api/projects/${a.projectId}/shipments/bulk` }, async execute() { return { ok: false, error: "CSV bulk import must be sent through the attachment upload flow." }; } },
  { name: "shipments.update", description: "Update shipment assessment fields; status is recomputed by the domain route.", permission: "schedule:manage", mutating: true, input: updateShipment, transport: { kind: "http", method: "PATCH", path: (a) => `/api/shipments/${a.shipmentId}` }, async execute(ctx, args) { const { shipmentId, ...body } = args as { shipmentId: string; [key: string]: unknown }; return callProjectRoute(ctx, "PATCH", () => `/api/shipments/${shipmentId}`, body, "shipmentDetail"); } },
  { name: "shipment_plans.act", description: "Generate, approve, reject, or materialize a shipment plan; approval and materialization remain explicit domain states.", permission: "schedule:manage", mutating: true, input: planAction, transport: { kind: "http", method: "POST", path: (a) => `/api/projects/${a.projectId}/shipment-plans` }, async execute(ctx, args) { return callProjectRoute(ctx, "POST", (a) => `/api/projects/${a.projectId}/shipment-plans`, args, "shipmentTable"); } }
];
