import { z } from "zod";
import { callProjectRoute } from "@/lib/copilot/invoke";
import { createComplianceCheck } from "@/lib/compliance/create-check";
import type { CopilotTool } from "@/lib/copilot/types";
export const tools: CopilotTool[] = [
  { name: "compliance.scan", description: "Scan accepted requirements against candidate controlled targets; results remain proposed and may be queued.", permission: "requirement:review", rateLimit: "ai", mutating: true, input: z.object({ requirementIds: z.array(z.string().uuid()).max(200).optional(), limit: z.number().int().positive().max(20).optional() }), transport: { kind: "http", method: "POST", path: (a) => `/api/projects/${a.projectId}/compliance/scan` }, async execute(ctx, args) { return callProjectRoute(ctx, "POST", (a) => `/api/projects/${a.projectId}/compliance/scan`, args, "complianceSummary"); } },
  { name: "compliance.check_one", description: "Create one proposed compliance comparison from exact requirement and target citations.", permission: "requirement:review", rateLimit: "ai", mutating: true, input: z.object({ requirementId: z.string().uuid(), targetSourceRegionId: z.string().uuid(), precedentId: z.string().uuid().optional() }), transport: { kind: "lib" }, async execute(ctx, args) { return { ok: true, data: await createComplianceCheck({ projectId: ctx.projectId, requirementId: (args as any).requirementId, targetSourceRegionId: (args as any).targetSourceRegionId, precedentId: (args as any).precedentId, actorId: ctx.userId }), render: "complianceSummary" }; } },
  { name: "cx.generate_checklist", description: "Generate a draft Cx checklist from completed controlled standards; it remains queued or draft until human acceptance.", permission: "evidence:capture", mutating: true, input: z.object({ systemId: z.string().uuid(), gateId: z.string().uuid(), assetId: z.string().uuid(), title: z.string().trim().min(3).max(250), standardVersionIds: z.array(z.string().uuid()).min(1).max(20) }), transport: { kind: "http", method: "POST", path: (a) => `/api/projects/${a.projectId}/cx/checklists` }, async execute(ctx, args) { return callProjectRoute(ctx, "POST", (a) => `/api/projects/${a.projectId}/cx/checklists`, args, "checklistSteps"); } },
  { name: "cx.record_reading", description: "Record a reading only; the domain route computes the proposed verdict and narrative steps require human review.", permission: "evidence:capture", mutating: true, input: z.object({ checklistId: z.string().uuid(), stepId: z.string().uuid(), value: z.number().finite().optional(), boolean: z.boolean().optional(), text: z.string().max(5000).optional() }), transport: { kind: "http", method: "POST", path: (a) => `/api/cx/checklists/${a.checklistId}/steps/${a.stepId}/reading` }, async execute(ctx, args) { const { checklistId, stepId, ...body } = args as any; return callProjectRoute(ctx, "POST", () => `/api/cx/checklists/${checklistId}/steps/${stepId}/reading`, body); } },
  { name: "cx.draft_report", description: "Draft a Cx report from a test record; the report is not approved by this tool.", permission: "evidence:capture", mutating: true, input: z.object({ testRecordId: z.string().uuid() }), transport: { kind: "http", method: "POST", path: (a) => `/api/cx/test-records/${a.testRecordId}/report` }, async execute(ctx, args) { return callProjectRoute(ctx, "POST", (a) => `/api/cx/test-records/${a.testRecordId}/report`, args); } }
];
