import { randomUUID } from "node:crypto";
import { eq } from "drizzle-orm";
import { NextResponse } from "next/server";
import { z } from "zod";
import { db } from "@/lib/db/client";
import { shipments } from "@/lib/db/schema";
import { processScheduleEvent } from "@/lib/events/process";
import { AccessError, requireProjectPermission } from "@/lib/projects/access";
import { calculateShipmentStatus } from "@/lib/supply/status";
const schema = z.object({ plannedEta: z.string().datetime().optional(), requiredOnSite: z.string().datetime().optional(), portCongestion: z.boolean().optional(), affectedTaskIds: z.array(z.string().uuid()).max(500).default([]) });
export async function PATCH(request: Request, { params }: { params: Promise<{ shipmentId: string }> }) { const { shipmentId } = await params; const parsed = schema.safeParse(await request.json().catch(() => null)); if (!parsed.success) return NextResponse.json({ error: "Shipment update is invalid." }, { status: 400 }); const shipment = await db.query.shipments.findFirst({ where: eq(shipments.id, shipmentId) }); if (!shipment) return NextResponse.json({ error: "Shipment not found." }, { status: 404 }); try { const actor = await requireProjectPermission(shipment.projectId, "schedule:manage"); const plannedEta = parsed.data.plannedEta ? new Date(parsed.data.plannedEta) : shipment.plannedEta; const requiredOnSite = parsed.data.requiredOnSite ? new Date(parsed.data.requiredOnSite) : shipment.requiredOnSite; const portCongestion = parsed.data.portCongestion ?? shipment.portCongestion; const calculated = calculateShipmentStatus({ plannedEta, requiredOnSite, portCongestion }); const [updated] = await db.update(shipments).set({ plannedEta, requiredOnSite, portCongestion, weatherAdjustedEta: calculated.weatherAdjustedEta, status: calculated.status, lastNotifiedStatus: calculated.status, updatedAt: new Date() }).where(eq(shipments.id, shipment.id)).returning(); if (calculated.status !== shipment.status) { const common = { eventId: randomUUID(), projectId: shipment.projectId, occurredAt: new Date().toISOString(), transitionId: `${shipment.status}-to-${calculated.status}-${Date.now()}` }; if (calculated.status === "green") await processScheduleEvent({ ...common, eventType: "SHIPMENT_RECOVERED", payload: { shipmentId: shipment.id, affectedTaskIds: parsed.data.affectedTaskIds, estimate: true } }, actor.userId); else await processScheduleEvent({ ...common, eventType: "SHIPMENT_DELAYED", payload: { shipmentId: shipment.id, status: calculated.status, affectedTaskIds: parsed.data.affectedTaskIds, estimate: true } }, actor.userId); } return NextResponse.json({ shipment: updated, transition: calculated.status === shipment.status ? null : `${shipment.status}_to_${calculated.status}`, estimate: true }); } catch (error) { return NextResponse.json({ error: error instanceof Error ? error.message : "Unable to update shipment." }, { status: error instanceof AccessError ? error.status : 500 }); } }
