"use client";

import { useMemo, useState } from "react";
import { BadgeDollarSign, Save, Sparkles } from "lucide-react";
import { baseFinancialInputs, calculateFinancialModel, type FinancialInputs } from "@/lib/financial/model";

const scenarios: Record<string, FinancialInputs> = {
  "5 MW Base Case": baseFinancialInputs,
  "25 MW Full Build": { ...baseFinancialInputs, contractedPowerMw: 25, utilizationPct: 88, planningBudgetUsdMw: 5_500_000 },
  "Conservative": { ...baseFinancialInputs, utilizationPct: 65, leaseRateUsdMwMonth: 175_000, powerCostUsdKwh: 0.065, planningBudgetUsdMw: 7_000_000, pue: 1.45, discountRatePct: 11 }
};
const labels: Array<[keyof FinancialInputs, string, number, number, number, string]> = [
  ["contractedPowerMw", "Contracted Power", .1, 50, .1, "MW"], ["utilizationPct", "Average Utilization", 1, 100, 1, "%"], ["leaseRateUsdMwMonth", "Lease Rate", 10_000, 500_000, 5_000, "USD / MW / month"], ["powerCostUsdKwh", "Power Cost", .01, .20, .001, "USD / kWh"], ["planningBudgetUsdMw", "Planning Budget", 1_000_000, 15_000_000, 100_000, "USD / MW"], ["pue", "PUE (Power Efficiency)", 1.1, 2, .01, "ratio"], ["discountRatePct", "Discount Rate (WACC)", 1, 25, .5, "%"], ["analysisPeriodYears", "Analysis Period", 1, 30, 1, "years"], ["usdInrRate", "USD → INR display rate", 60, 120, .1, "₹ / USD"]
];

const asInputs = (model: Partial<Record<keyof FinancialInputs, string | number>> | null): FinancialInputs => Object.fromEntries(Object.entries(baseFinancialInputs).map(([key, fallback]) => [key, Number(model?.[key as keyof FinancialInputs] ?? fallback)])) as FinancialInputs;
export function FinancialModeler({ projectId, initialModel }: { projectId: string; initialModel: Partial<Record<keyof FinancialInputs, string | number>> | null }) {
  const [inputs, setInputs] = useState(() => asInputs(initialModel)); const [currency, setCurrency] = useState<"INR" | "USD">("INR"); const [status, setStatus] = useState(initialModel ? "Saved model loaded. USD remains the canonical stored currency." : "Scenario assumptions are local until you save them."); const [saving, setSaving] = useState(false);
  const result = useMemo(() => calculateFinancialModel(inputs), [inputs]); const multiplier = currency === "INR" ? inputs.usdInrRate : 1;
  const money = (value: number, digits = 1) => new Intl.NumberFormat(currency === "INR" ? "en-IN" : "en-US", { style: "currency", currency: currency === "INR" ? "INR" : "USD", notation: "compact", maximumFractionDigits: digits }).format(value * multiplier);
  const set = (key: keyof FinancialInputs, value: number) => setInputs((old) => ({ ...old, [key]: value }));
  const save = async () => { setSaving(true); try { const response = await fetch(`/api/projects/${projectId}/financial-model`, { method: "PUT", headers: { "content-type": "application/json" }, body: JSON.stringify(inputs) }); const body = await response.json(); if (!response.ok) throw new Error(body.error); setStatus("Saved. All financial assumptions are stored in USD; INR is display conversion only."); } catch (error) { setStatus(error instanceof Error ? error.message : "Unable to save financial model."); } finally { setSaving(false); } };
  const sensitivity = [65, 75, 85, 95].map((utilization) => ({ utilization, npv: calculateFinancialModel({ ...inputs, utilizationPct: utilization }).npv, irr: calculateFinancialModel({ ...inputs, utilizationPct: utilization }).projectIrr }));
  return <section className="financial-modeler">
    <div className="financial-notice"><Sparkles size={17} /><span><b>Indicative planning model only.</b> This is not financial advice; validate utility tariffs, construction costs, financing, tax, occupancy and contracts with qualified advisors.</span></div>
    <section className="financial-toolbar surface"><div><p className="eyebrow">Quick scenarios</p><div className="scenario-buttons">{Object.keys(scenarios).map((name) => <button type="button" key={name} onClick={() => { setInputs({ ...scenarios[name] }); setStatus(`${name} loaded locally. Save to commit it to this project.`); }}>{name}</button>)}</div></div><div className="currency-switch" aria-label="Display currency"><button className={currency === "INR" ? "is-active" : ""} type="button" onClick={() => setCurrency("INR")}>₹ INR</button><button className={currency === "USD" ? "is-active" : ""} type="button" onClick={() => setCurrency("USD")}>$ USD</button></div><button className="button button-primary" type="button" onClick={save} disabled={saving}><Save size={16} />{saving ? "Saving…" : "Save USD model"}</button></section>
    <section className="financial-layout"><form className="financial-inputs surface"><header><p className="eyebrow">Assumptions</p><h2>Data center economics</h2><p>Adjust any input; every output below updates immediately.</p></header>{labels.map(([key, label, min, max, step, suffix]) => <label key={key}><span><b>{label}</b><small>{suffix}</small></span><input type="range" min={min} max={max} step={step} value={inputs[key]} onChange={(event) => set(key, Number(event.target.value))} /><input aria-label={label} type="number" min={min} max={max} step={step} value={inputs[key]} onChange={(event) => set(key, Number(event.target.value))} /></label>)}</form>
      <div className="financial-results"><section className="financial-kpis"><Metric label="Annual Revenue" value={money(result.annualRevenue)} detail={`${money(result.monthlyRevenue)}/month`} /><Metric label="Annual Gross Profit" value={money(result.annualGrossProfit)} detail={`${result.grossMarginPct.toFixed(0)}% gross margin`} /><Metric label={`${inputs.analysisPeriodYears}-Year NPV`} value={money(result.npv)} detail={`at ${inputs.discountRatePct}% discount rate`} /><Metric label="Project IRR" value={result.projectIrr === null ? "—" : `${(result.projectIrr * 100).toFixed(1)}%`} detail="unlevered planning return" /><Metric label="Planning Budget" value={money(result.planningBudget)} detail={`${money(inputs.planningBudgetUsdMw)} / MW`} /><Metric label="Payback Period" value={result.paybackYears ? `${result.paybackYears.toFixed(1)} yrs` : "—"} detail="budget recovered from gross profit" /></section>
        <section className="surface financial-pnl"><header><p className="eyebrow">Annual P&L summary</p><h2>Revenue, energy, and gross profit</h2></header><div><span>Gross revenue</span><b>{money(result.annualRevenue)}</b></div><div><span>− Power costs</span><b>−{money(result.annualPowerCost)}</b></div><div className="financial-total"><span>= Gross profit</span><b>{money(result.annualGrossProfit)}</b></div></section>
        <section className="surface financial-sensitivity"><header><p className="eyebrow">Live sensitivity</p><h2>Utilization impact</h2></header><div className="sensitivity-table"><div><span>Utilization</span><span>NPV</span><span>IRR</span></div>{sensitivity.map((row) => <div key={row.utilization} className={row.utilization === inputs.utilizationPct ? "is-current" : ""}><b>{row.utilization}%</b><span>{money(row.npv)}</span><span>{row.irr === null ? "—" : `${(row.irr * 100).toFixed(1)}%`}</span></div>)}</div></section>
      </div>
    </section>
    <section className="surface financial-drivers"><BadgeDollarSign size={22} /><div><p className="eyebrow">Key drivers</p><h2>What is driving this planning case</h2><p>At <b>{inputs.utilizationPct}%</b> utilization of <b>{inputs.contractedPowerMw} MW</b> contracted capacity, effective IT load is <b>{result.effectiveItLoadMw.toFixed(1)} MW</b>. A PUE of <b>{inputs.pue.toFixed(2)}</b> produces <b>{result.totalPowerDrawMw.toFixed(1)} MW</b> total draw. Power costs consume <b>{(result.annualPowerCost / result.annualRevenue * 100 || 0).toFixed(0)}%</b> of gross revenue; payback is led by the <b>{money(result.planningBudget)}</b> planning budget and current lease rate.</p></div></section><p className="financial-status" role="status">{status}</p>
  </section>;
}
function Metric({ label, value, detail }: { label: string; value: string; detail: string }) { return <article className="surface"><p>{label}</p><strong>{value}</strong><small>{detail}</small></article>; }
