"use client";

import { FormEvent, useCallback, useEffect, useState } from "react";
import { useRouter } from "next/navigation";

type Signal = { id: string; taskId: string; pollCycleId: string; signalType: string; status: string; dataAvailable: boolean; source: string; value: unknown; unavailableReason: string | null; observedAt: Date };
type Risk = { id: string; taskId: string; riskType: string; status: string; probability: string; estimatedDelayHours: number; mitigationOptions: unknown; reviewState: string; reviewNote: string | null; mitigationDisposition: string; version: number; observedAt: Date; scheduleEventId: string | null };
type LiveEvent =
  | { kind: "risk"; signal: Signal; taskName: string; at: string }
  | { kind: "ais"; label: string; detail: string; positionSource: string; mmsi: string | null; at: string }
  | { kind: "weather"; label: string; detail: string; weatherDelayFactor: string; status: string; at: string };

function label(value: string) { return value.replaceAll("_", " "); }
function kindLabel(kind: LiveEvent["kind"]) { return kind === "ais" ? "AIS position" : kind === "weather" ? "Weather" : "Risk signal"; }

export function PredictiveRiskWorkbench({ projectId, hasCurrentVersion, risks }: { projectId: string; hasCurrentVersion: boolean; risks: Array<{ risk: Risk; taskName: string; eventProcessingStatus: string | null }> }) {
  const router = useRouter(); const [tab, setTab] = useState<"signals" | "risks">("signals"); const [message, setMessage] = useState(""); const [saving, setSaving] = useState(false);
  const [liveEvents, setLiveEvents] = useState<LiveEvent[]>([]);
  const loadLiveEvents = useCallback(async () => {
    try { const response = await fetch(`/api/projects/${projectId}/schedule/live-events`); if (!response.ok) return; const body = await response.json(); setLiveEvents(Array.isArray(body.items) ? body.items : []); } catch { /* transient network error; the seeded cards remain visible */ }
  }, [projectId]);
  useEffect(() => { if (tab !== "signals") return; loadLiveEvents(); const timer = setInterval(loadLiveEvents, 15_000); return () => clearInterval(timer); }, [tab, loadLiveEvents]);

  async function pollJob(jobId: string) { for (let attempt = 0; attempt < 120; attempt += 1) { const response = await fetch(`/api/jobs/${jobId}`); const body = await response.json(); if (body.job?.status === "completed") return body.job; if (body.job?.status === "failed") throw new Error(body.job.error ?? "Risk poll failed."); await new Promise((resolve) => setTimeout(resolve, 150)); } throw new Error("Risk poll timed out."); }
  async function runPoll() {
    setSaving(true); setMessage("");
    try { const response = await fetch(`/api/projects/${projectId}/schedule/risks`, { method: "POST", headers: { "content-type": "application/json" }, body: "{}" }); const body = await response.json(); if (!response.ok) throw new Error(body.error ?? "Unable to start polling."); const job = body.status === "completed" ? { result: body.result } : await pollJob(body.pollJobId); setMessage(`Poll complete: ${job.result.availableCount} available, ${job.result.unavailableCount} unavailable, ${job.result.emittedCount} material change(s), ${job.result.resolvedCount} resolved.`); router.refresh(); } catch (error) { setMessage(error instanceof Error ? error.message : "Risk poll failed."); } finally { setSaving(false); }
  }
  async function review(event: FormEvent<HTMLFormElement>, risk: Risk, action: "acknowledge" | "dismiss") {
    event.preventDefault(); const form = new FormData(event.currentTarget); setSaving(true); setMessage("");
    const response = await fetch(`/api/schedule/risks/${risk.id}/review`, { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ action, expectedVersion: risk.version, note: form.get("note") }) }); const body = await response.json(); setMessage(response.ok ? body.authority : body.error ?? "Review failed."); setSaving(false); if (response.ok) router.refresh();
  }

  return <section className="surface risk-workbench" aria-labelledby="predictive-risk-heading">
    <header><div><span className="eyebrow">Predictive schedule risk</span><h2 id="predictive-risk-heading">Live signals and advisory delays</h2><p>Polling records every source outcome. Only deterministic material changes emit an alert; this engine never invokes CP-SAT or changes a date.</p></div><button className="button button-secondary" onClick={runPoll} disabled={saving || !hasCurrentVersion}>{saving ? "Polling…" : "Poll risk signals"}</button></header>
    {!hasCurrentVersion && <p className="infeasibility-banner">Create an accepted-task schedule baseline before polling task-linked risk signals.</p>}
    {message && <p className="form-message" role="status">{message}</p>}
    <div className="workflow-tabs" role="tablist" aria-label="Predictive risk views"><button type="button" className={tab === "signals" ? "is-active" : ""} onClick={() => setTab("signals")} role="tab" aria-selected={tab === "signals"}>Live Events</button><button type="button" className={tab === "risks" ? "is-active" : ""} onClick={() => setTab("risks")} role="tab" aria-selected={tab === "risks"}>Delays / Risks</button></div>
    {tab === "signals" && <div className="risk-grid live-events-stream">{liveEvents.map((event, index) => <article className={`risk-card live-event-card kind-${event.kind}`} key={`${event.kind}-${event.at}-${index}`}><div className="status-row"><span className={`source-status ${event.kind === "risk" ? (event.signal.dataAvailable ? "ready" : "failed") : "processed"}`}>{event.kind === "risk" ? `Risk: ${label(event.signal.signalType)}` : kindLabel(event.kind)}</span><span className="mono-label">{new Date(event.at).toLocaleTimeString()}</span></div><h3>{event.kind === "risk" ? event.taskName : event.label}</h3><p>{event.kind === "risk" ? (event.signal.dataAvailable ? `${label(event.signal.signalType)} recorded from ${event.signal.source}.` : event.signal.unavailableReason ?? "No data returned for this poll cycle.") : event.detail}</p><small>{new Date(event.at).toLocaleString()}{event.kind === "ais" && event.mmsi ? ` · MMSI ${event.mmsi}` : ""}{event.kind === "risk" ? ` · cycle ${event.signal.pollCycleId.slice(0, 8)}` : ""}</small></article>)}{!liveEvents.length && <article className="empty-state"><h3>Awaiting live poll activity</h3><p>The recurring supply and risk polls stream AIS, weather, and risk observations here as they land.</p></article>}</div>}
  {tab === "risks" && <div className="risk-grid">{risks.map(({ risk, taskName, eventProcessingStatus }) => { const options = Array.isArray(risk.mitigationOptions) ? risk.mitigationOptions : []; return <article className="risk-card" key={risk.id}><div className="status-row"><span className={`source-status ${risk.status === "active" ? "failed" : risk.status === "resolved" ? "ready" : "pending"}`}>{risk.status}</span><span className="mono-label">{label(risk.riskType)} · {Math.round(Number(risk.probability) * 100)}% · {risk.estimatedDelayHours}h estimate</span></div><h3>{taskName}</h3><p className="advisory-note">Advisory only — mitigation options are not selected or applied by the engine.</p><ul>{options.map((option: any, idx: number) => { const key = option.id || option.option || `mitigation-${idx}`; const title = option.label || option.option || ""; const detail = option.description || (option.cost ? `Cost: ${option.cost}` : ""); return <li key={key}><strong>{title}</strong><span>{detail}</span></li>; })}</ul><small>Event: {eventProcessingStatus ?? "not emitted"} · Review: {label(risk.reviewState)} · {new Date(risk.observedAt).toLocaleString()}</small>{risk.reviewNote && <p><strong>Reviewer rationale:</strong> {risk.reviewNote}</p>}{risk.reviewState === "proposed" && risk.status === "active" && <form className="risk-review-form" onSubmit={(event) => review(event, risk, "acknowledge")}><label>Review rationale<textarea name="note" required minLength={10} placeholder="Record awareness or explain dismissal. No mitigation is applied here." /></label><div className="review-actions"><button className="button button-primary" disabled={saving}>Acknowledge only</button><button type="button" className="button button-inverted" disabled={saving} onClick={(event) => { const form = event.currentTarget.form; if (form?.reportValidity()) review({ preventDefault() {}, currentTarget: form } as unknown as FormEvent<HTMLFormElement>, risk, "dismiss"); }}>Dismiss risk</button></div></form>}</article>; })}{!risks.length && <article className="empty-state"><h3>No material schedule risks</h3><p>This is not a guarantee. Review Live Events for source freshness and explicit unavailable states.</p></article>}</div>}
  </section>;
}
