"use client";
import { FormEvent, useEffect, useState } from "react";
type Profile = { user: { id: string; email: string; displayName: string; totpEnabled: boolean; provider: string }; memberships: Array<{ projectId: string; projectName: string; projectCode: string; role: string }> };
export function ProfilePanel() {
  const [profile, setProfile] = useState<Profile | null>(null); const [name, setName] = useState(""); const [message, setMessage] = useState("Loading your persisted profile…");
  const [enrollment, setEnrollment] = useState<{ secret: string; uri: string } | null>(null); const [password, setPassword] = useState(""); const [token, setToken] = useState("");
  useEffect(() => { fetch("/api/profile").then(async (response) => { const body = await response.json(); if (!response.ok) throw new Error(body.error); setProfile(body); setName(body.user.displayName); setMessage(""); }).catch((error) => setMessage(error.message)); }, []);
  async function save(event: FormEvent) { event.preventDefault(); const response = await fetch("/api/profile", { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ displayName: name }) }); const body = await response.json(); setMessage(response.ok ? "Profile updated." : body.error); if (response.ok && profile) setProfile({ ...profile, user: { ...profile.user, displayName: body.user.displayName } }); }
  async function enroll() { const response = await fetch("/api/auth/totp/enroll", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ password }) }); const body = await response.json(); if (!response.ok) return setMessage(body.error); setEnrollment(body); setMessage("Add this secret to your authenticator, then verify a code."); }
  async function verify() { const response = await fetch("/api/auth/totp/verify", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ token }) }); const body = await response.json(); if (!response.ok) return setMessage(body.error); if (profile) setProfile({ ...profile, user: { ...profile.user, totpEnabled: true } }); setEnrollment(null); setPassword(""); setToken(""); setMessage("Two-factor authentication enabled."); }
  async function logout() { await fetch("/api/auth/logout", { method: "POST" }); location.assign("/login"); }
  return <div className="workflow-stack"><form className="surface profile-form" onSubmit={save}><div><p className="eyebrow">Identity</p><h2>{profile?.user.displayName ?? "Profile"}</h2><p>{profile?.user.email ?? message}</p></div><label>Display name<input value={name} onChange={(event) => setName(event.target.value)} minLength={2} disabled={!profile} /></label><button className="button button-primary" disabled={!profile}>Save profile</button>{message && <p className="form-message">{message}</p>}{profile && <p className="workflow-hint">Provider: {profile.user.provider} · TOTP: {profile.user.totpEnabled ? "enabled" : profile.user.provider === "credentials" ? "not enabled" : "managed by your identity provider"}</p>}</form>{profile?.user.provider === "credentials" && !profile.user.totpEnabled && <section className="surface profile-form"><div><p className="eyebrow">Approval security</p><h2>Enable authenticator codes</h2><p className="workflow-hint">Required for high-authority gate decisions.</p></div><label>{enrollment ? "Six-digit code" : "Confirm password"}<input type={enrollment ? "text" : "password"} value={enrollment ? token : password} onChange={(event) => enrollment ? setToken(event.target.value) : setPassword(event.target.value)} /></label><button type="button" className="button button-secondary" onClick={enrollment ? verify : enroll}>{enrollment ? "Verify code" : "Start enrollment"}</button>{enrollment && <p className="form-message mono">Secret: {enrollment.secret}</p>}</section>}<section className="workflow-grid">{profile?.memberships.map((membership) => <article className="surface workflow-card" key={membership.projectId}><span className="source-status processed">{membership.role.replaceAll("_", " ")}</span><h2>{membership.projectName}</h2><p>{membership.projectCode}</p></article>)}</section>{profile?.user.provider === "credentials" && <button className="button button-outline" onClick={logout}>Sign out</button>}</div>;
}
