"use client";
import { FormEvent, useState } from "react";
import { useRouter } from "next/navigation";
type Task = { id: string; name: string; durationHours: number; reviewState: string };
type Version = { id: string; versionNumber: number; solverStatus: string; objectiveHours: number | null; explanation: string | null; assignments: Array<{ id: string; taskName: string; startAt: Date | string; endAt: Date | string; isCritical: boolean }> };
export function ScheduleWorkbench({ projectId, tasks, versions }: { projectId: string; tasks: Task[]; versions: Version[] }) {
  const router = useRouter(); const [message, setMessage] = useState("");
  async function createTask(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); const response = await fetch(`/api/projects/${projectId}/schedule/tasks`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ name: form.get("name"), durationHours: Number(form.get("durationHours")), earliestStart: form.get("earliestStart") ? new Date(String(form.get("earliestStart"))).toISOString() : undefined, deadline: form.get("deadline") ? new Date(String(form.get("deadline"))).toISOString() : undefined }) }); const body = await response.json(); setMessage(response.ok ? "Task proposal created." : body.error); if (response.ok) { event.currentTarget.reset(); router.refresh(); } }
  async function review(taskId: string, decision: "accept" | "reject") { const response = await fetch(`/api/schedule/tasks/${taskId}/review`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ decision, note: `${decision}ed from schedule workbench` }) }); const body = await response.json(); setMessage(response.ok ? `Task ${decision}ed.` : body.error); if (response.ok) router.refresh(); }
  async function solve() { setMessage("Running deterministic CP-SAT solve…"); const response = await fetch(`/api/projects/${projectId}/schedule/versions`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ horizonStart: new Date().toISOString(), reason: "Manual baseline solve from schedule workbench" }) }); const body = await response.json(); setMessage(response.ok ? `Saved schedule version ${body.version.versionNumber}.` : body.error ?? body.solver?.bottlenecks?.join(" ")); router.refresh(); }
  return <div className="workflow-stack"><form className="surface workflow-form schedule-form" onSubmit={createTask}><label>Task name<input name="name" required minLength={3} /></label><label>Duration hours<input name="durationHours" type="number" min={1} required /></label><label>Earliest start<input name="earliestStart" type="datetime-local" /></label><label>Deadline<input name="deadline" type="datetime-local" /></label><button className="button button-primary">Propose task</button>{message && <p className="form-message">{message}</p>}</form><section className="two-column"><article className="surface workflow-card"><div className="section-heading"><div><p className="eyebrow">Human review queue</p><h2>Schedule inputs</h2></div><button className="button button-secondary" onClick={solve} disabled={!tasks.some((task) => task.reviewState === "accepted")}>Solve baseline</button></div><div className="workflow-stack">{tasks.map((task) => <div className="requirement" key={task.id}><span className={`source-status ${task.reviewState === "accepted" ? "processed" : "pending"}`}>{task.reviewState}</span><p>{task.name}</p><small>{task.durationHours} hours</small>{task.reviewState === "proposed" && <div className="review-actions"><button className="button button-outline" onClick={() => review(task.id, "reject")}>Reject</button><button className="button button-primary" onClick={() => review(task.id, "accept")}>Accept</button></div>}</div>)}</div></article><article className="surface workflow-card"><p className="eyebrow">Immutable history</p><h2>Schedule versions</h2><div className="workflow-stack">{versions.map((version) => <div className="requirement" key={version.id}><span className={`source-status ${["OPTIMAL", "FEASIBLE"].includes(version.solverStatus) ? "processed" : "pending"}`}>{version.solverStatus}</span><p>Version {version.versionNumber} · {version.objectiveHours ?? "—"} hours</p><small>{version.explanation}</small><div className="table-wrap"><table><tbody>{version.assignments.map((item) => <tr key={item.id}><td><b>{item.taskName}</b></td><td>{new Intl.DateTimeFormat("en-IN", { dateStyle: "medium", timeStyle: "short" }).format(new Date(item.startAt))}</td><td>{item.isCritical ? "Critical" : "Scheduled"}</td></tr>)}</tbody></table></div></div>)}</div></article></section></div>;
}
