"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { AlertTriangle, CheckCircle2, GitCompareArrows, Network, Play, RefreshCw } from "lucide-react";

type Task = { id: string; name: string; durationHours: number; earliestStart: Date | string | null; deadline: Date | string | null; vendor: string | null; reviewState: string; confidence: string | null; validationIssues: unknown; reviewNote: string | null; updatedAt: Date | string };
type Resource = { id: string; name: string; capacity: number; unit: string; reviewState: string; confidence: string | null; validationIssues: unknown; updatedAt: Date | string };
type Dependency = { id: string; predecessorTaskId: string; successorTaskId: string; updatedAt: Date | string };
type Version = { id: string; versionNumber: number; parentVersionId: string | null; triggerEventId: string | null; solverStatus: string; solverVersion: string; objectiveHours: number | null; overrunHours: number; bottlenecks: unknown; explanation: string | null; explanationModelVersion: string | null; explanationGeneratedAt: Date | string | null; reason: string; createdAt: Date | string; assignments: Array<{ id: string; taskId: string; taskName: string; startAt: Date | string; endAt: Date | string; isCritical: boolean }> };
type ScheduleEvent = { id: string; eventType: string; occurredAt: Date | string; processingStatus: string; resultVersionId: string | null; processingError: string | null };
type Diff = { shiftedTasks: Array<{ taskId: string; taskName: string; beforeStart: string; afterStart: string; beforeEnd: string; afterEnd: string; shiftHours: number }>; added: unknown[]; removed: unknown[]; netDeadlineImpactHours: number; against: { versionNumber: number } | null; current: { versionNumber: number } };

const delay = (ms: number) => new Promise((resolve) => setTimeout(resolve, ms));
const issues = (value: unknown) => Array.isArray(value) ? value.map(String) : [];

export function ScheduleWorkbench({ projectId, tasks, resources, dependencies, versions, events, focusTaskId, focusVersionId }: { projectId: string; tasks: Task[]; resources: Resource[]; dependencies: Dependency[]; versions: Version[]; events: ScheduleEvent[]; focusTaskId?: string; focusVersionId?: string }) {
  const router = useRouter();
  const [tab, setTab] = useState<"inputs" | "board" | "history" | "events">(versions.length ? "board" : "inputs");
  const [message, setMessage] = useState("");
  const [saving, setSaving] = useState(false);
  const [diff, setDiff] = useState<Diff | null>(null);
  const acceptedTasks = tasks.filter((task) => task.reviewState === "accepted");
  const acceptedResources = resources.filter((resource) => resource.reviewState === "accepted");
  const current = versions[0];
  // A solved version is an immutable snapshot of the inputs at solve time, and
  // nothing re-solves it when a task, resource, or dependency later changes.
  // scheduleVersions.inputHash cannot be recomputed for comparison because the
  // horizon start it was hashed against is not persisted, so fall back to the
  // honest signal: accepted inputs modified after the version was solved.
  const staleInputs = useMemo(() => {
    if (!current) return [] as string[];
    const solvedAt = new Date(current.createdAt).getTime();
    const changed = (updatedAt: Date | string) => new Date(updatedAt).getTime() > solvedAt;
    return [
      ...tasks.filter((task) => task.reviewState === "accepted" && changed(task.updatedAt)).map((task) => task.name),
      ...resources.filter((resource) => resource.reviewState === "accepted" && changed(resource.updatedAt)).map((resource) => resource.name),
      ...dependencies.filter((dependency) => changed(dependency.updatedAt)).map(() => "a precedence link"),
    ];
  }, [current, tasks, resources, dependencies]);
  const taskById = new Map(tasks.map((task) => [task.id, task]));
  useEffect(() => {
    if (!focusTaskId && !focusVersionId) return;
    if (focusTaskId) setTab(versions.length ? "board" : "inputs");
    else setTab("history");
    const target = focusTaskId ? `task-${focusTaskId}` : `version-${focusVersionId}`;
    requestAnimationFrame(() => document.getElementById(target)?.scrollIntoView({ behavior: "smooth", block: "center" }));
  }, [focusTaskId, focusVersionId, versions.length]);

  async function json(url: string, method: string, body: Record<string, unknown>) {
    setSaving(true); const response = await fetch(url, { method, headers: { "content-type": "application/json" }, body: JSON.stringify(body) }); const result = await response.json().catch(() => ({})); setSaving(false); if (!response.ok) throw new Error(result.error ?? "Schedule operation failed."); return result;
  }

  async function createTask(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); const form = event.currentTarget; const values = new FormData(form); const resourceId = String(values.get("resourceId") || "");
    try { await json(`/api/projects/${projectId}/schedule/tasks`, "POST", { name: values.get("name"), durationHours: Number(values.get("durationHours")), earliestStart: values.get("earliestStart") ? new Date(String(values.get("earliestStart"))).toISOString() : undefined, deadline: values.get("deadline") ? new Date(String(values.get("deadline"))).toISOString() : undefined, deadlineType: values.get("deadline") ? values.get("deadlineType") : undefined, vendor: values.get("vendor") || undefined, resourceDemands: resourceId ? [{ resourceId, demand: Number(values.get("demand")) }] : [] }); form.reset(); setMessage("Human-authored task proposal created; explicit acceptance is still required."); router.refresh(); }
    catch (error) { setMessage(error instanceof Error ? error.message : "Task proposal failed."); }
  }
  async function createResource(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = event.currentTarget; const values = new FormData(form); try { await json(`/api/projects/${projectId}/schedule/resources`, "POST", { name: values.get("name"), capacity: Number(values.get("capacity")), unit: values.get("unit"), validationIssues: [] }); form.reset(); setMessage("Resource-capacity proposal created for review."); router.refresh(); } catch (error) { setMessage(error instanceof Error ? error.message : "Resource proposal failed."); } }
  async function reviewTask(task: Task, action: "accept" | "edit" | "reject") { try { await json(`/api/schedule/tasks/${task.id}/review`, "POST", { action, resolveValidationIssues: action === "edit", note: action === "edit" ? "Reviewer explicitly resolved all flagged extraction fields." : `${action}ed in schedule review queue.` }); setMessage(`Task ${action} recorded.`); router.refresh(); } catch (error) { setMessage(error instanceof Error ? error.message : "Task review failed."); } }
  async function reviewResource(resource: Resource, action: "accept" | "edit" | "reject") { try { await json(`/api/schedule/resources/${resource.id}/review`, "POST", { action, resolveValidationIssues: action === "edit", note: action === "edit" ? "Reviewer explicitly resolved all flagged capacity fields." : `${action}ed in resource review queue.` }); setMessage(`Resource ${action} recorded.`); router.refresh(); } catch (error) { setMessage(error instanceof Error ? error.message : "Resource review failed."); } }
  async function createDependency(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = event.currentTarget; const values = new FormData(form); try { await json(`/api/projects/${projectId}/schedule/dependencies`, "POST", { predecessorTaskId: values.get("predecessorTaskId"), successorTaskId: values.get("successorTaskId") }); form.reset(); setMessage("Accepted-task precedence edge created."); router.refresh(); } catch (error) { setMessage(error instanceof Error ? error.message : "Dependency failed."); } }
  async function solve() {
    setMessage("Baseline queued for deterministic CP-SAT solve…");
    try {
      const result = await json(`/api/projects/${projectId}/schedule/baseline`, "POST", { horizonStart: new Date().toISOString(), reason: versions.length ? "Manual controlled re-baseline" : "Initial controlled baseline", idempotencyKey: `ui-baseline:${crypto.randomUUID()}` });
      if (result.status === "completed") { setMessage("Deterministic baseline saved."); router.refresh(); return; }
      for (let attempt = 0; attempt < 90; attempt += 1) { await delay(1000); const response = await fetch(`/api/jobs/${result.solveJobId}`); const body = await response.json(); if (body.job?.status === "completed") { setMessage(`Schedule version saved by job ${result.solveJobId}.`); router.refresh(); setTab("board"); return; } if (body.job?.status === "failed") throw new Error(`SOLVE_FAILED · ${body.job.error} · job ${result.solveJobId}`); }
      throw new Error(`Solve is still processing. Track job ${result.solveJobId}.`);
    } catch (error) { setMessage(error instanceof Error ? error.message : "Baseline solve failed."); }
  }
  async function compare(versionId: string, againstId?: string) { const response = await fetch(`/api/schedule/versions/${versionId}/diff${againstId ? `?against=${againstId}` : ""}`); const body = await response.json(); if (!response.ok) return setMessage(body.error); setDiff(body.diff); setTab("history"); }

  const gantt = useMemo(() => {
    if (!current?.assignments.length) return [];
    const starts = current.assignments.map((item) => new Date(item.startAt).getTime()); const ends = current.assignments.map((item) => new Date(item.endAt).getTime()); const min = Math.min(...starts); const max = Math.max(...ends); const span = Math.max(max - min, 1);
    return current.assignments.map((item) => ({ ...item, left: (new Date(item.startAt).getTime() - min) / span * 100, width: Math.max((new Date(item.endAt).getTime() - new Date(item.startAt).getTime()) / span * 100, 1.5) }));
  }, [current]);

  return <div className="workflow-stack">
    <nav className="workflow-tabs" aria-label="Schedule sections"><button className={tab === "inputs" ? "is-active" : ""} onClick={() => setTab("inputs")}>Inputs & review</button><button className={tab === "board" ? "is-active" : ""} onClick={() => setTab("board")}>Current schedule</button><button className={tab === "history" ? "is-active" : ""} onClick={() => setTab("history")}>History & diff</button><button className={tab === "events" ? "is-active" : ""} onClick={() => setTab("events")}>Event log</button></nav>
    {message && <p className="surface inline-feedback" role="status">{message}</p>}
    {!!staleInputs.length && <p className="surface inline-feedback is-warning" role="status"><AlertTriangle size={15} /> Version {current?.versionNumber} was solved before {staleInputs.length} accepted input{staleInputs.length === 1 ? " was" : "s were"} changed ({[...new Set(staleInputs)].slice(0, 3).join(", ")}{staleInputs.length > 3 ? ", …" : ""}). The dates and critical path below are from the earlier inputs — re-run CP-SAT to bring them current.</p>}
    {tab === "inputs" && <div className="workflow-stack">
      <section className="two-column"><form className="surface compact-form" onSubmit={createResource}><div><p className="eyebrow">Capacity proposal</p><h2>Add resource</h2></div><label>Name<input name="name" required placeholder="Electrical commissioning crew" /></label><label>Capacity<input name="capacity" type="number" min="1" required /></label><label>Unit<input name="unit" defaultValue="crew" required /></label><button className="button button-primary" disabled={saving}>Propose resource</button></form><form className="surface compact-form" onSubmit={createTask}><div><p className="eyebrow">Task proposal</p><h2>Add schedule task</h2></div><label>Name<input name="name" required minLength={3} /></label><label>Duration hours<input name="durationHours" type="number" min="1" required /></label><label>Vendor<input name="vendor" /></label><label>Earliest start<input name="earliestStart" type="datetime-local" /></label><label>Deadline<input name="deadline" type="datetime-local" /></label><label>Deadline type<select name="deadlineType" defaultValue="soft"><option value="soft">Soft</option><option value="hard">Hard contractual</option></select></label><label>Resource demand<select name="resourceId"><option value="">No constrained resource</option>{resources.map((resource) => <option value={resource.id} key={resource.id}>{resource.name} ({resource.reviewState})</option>)}</select></label><label>Demand quantity<input name="demand" type="number" min="1" defaultValue="1" /></label><button className="button button-primary" disabled={saving}>Propose task</button></form></section>
      <section className="two-column"><article className="surface workflow-card"><div className="section-heading"><div><p className="eyebrow">Mandatory human review</p><h2>Resources</h2></div><span className="review-count">{resources.filter((item) => ["proposed", "edited"].includes(item.reviewState)).length}</span></div>{resources.map((resource) => <div className="requirement" key={resource.id}><span className={`source-status ${resource.reviewState === "accepted" ? "processed" : "pending"}`}>{resource.reviewState}</span><p>{resource.name}</p><small>{resource.capacity} {resource.unit} · confidence {resource.confidence ?? "human-authored"}</small>{issues(resource.validationIssues).map((issue) => <span className="validation-flag" key={issue}><AlertTriangle size={13} />{issue}</span>)}{["proposed", "edited"].includes(resource.reviewState) && <div className="review-actions"><button className="button button-outline" onClick={() => reviewResource(resource, "reject")}>Reject</button>{issues(resource.validationIssues).length ? <button className="button button-secondary" onClick={() => reviewResource(resource, "edit")}>Resolve flags</button> : <button className="button button-primary" onClick={() => reviewResource(resource, "accept")}>Accept capacity</button>}</div>}</div>)}</article><article className="surface workflow-card"><div className="section-heading"><div><p className="eyebrow">Mandatory human review</p><h2>Tasks</h2></div><span className="review-count">{tasks.filter((item) => ["proposed", "edited"].includes(item.reviewState)).length}</span></div>{tasks.map((task) => <div className="requirement" key={task.id}><span className={`source-status ${task.reviewState === "accepted" ? "processed" : "pending"}`}>{task.reviewState}</span><p>{task.name}</p><small>{task.durationHours} hours · {task.vendor ?? "no vendor"} · confidence {task.confidence ?? "human-authored"}</small>{issues(task.validationIssues).map((issue) => <span className="validation-flag" key={issue}><AlertTriangle size={13} />{issue}</span>)}{["proposed", "edited"].includes(task.reviewState) && <div className="review-actions"><button className="button button-outline" onClick={() => reviewTask(task, "reject")}>Reject</button>{issues(task.validationIssues).length ? <button className="button button-secondary" onClick={() => reviewTask(task, "edit")}>Resolve flags</button> : <button className="button button-primary" onClick={() => reviewTask(task, "accept")}>Accept task</button>}</div>}</div>)}</article></section>
      <form className="surface dependency-form" onSubmit={createDependency}><div><p className="eyebrow">DAG validation</p><h2>Add accepted-task precedence</h2></div><label>Predecessor<select name="predecessorTaskId" required><option value="">Select task</option>{acceptedTasks.map((task) => <option value={task.id} key={task.id}>{task.name}</option>)}</select></label><Network size={20} /><label>Successor<select name="successorTaskId" required><option value="">Select task</option>{acceptedTasks.map((task) => <option value={task.id} key={task.id}>{task.name}</option>)}</select></label><button className="button button-secondary" disabled={acceptedTasks.length < 2}>Add edge</button><div className="dependency-list">{dependencies.map((edge) => <span key={edge.id}>{taskById.get(edge.predecessorTaskId)?.name} → {taskById.get(edge.successorTaskId)?.name}</span>)}</div></form>
      <section className="surface solve-bar"><div><p className="eyebrow">Deterministic authority</p><h2>CP-SAT baseline</h2><p>{acceptedTasks.length} accepted tasks · {acceptedResources.length} accepted resources</p></div><button className="button button-primary" onClick={solve} disabled={saving || !acceptedTasks.length}><Play size={16} /> Solve immutable baseline</button></section>
    </div>}
    {tab === "board" && (!current ? <section className="surface empty-state"><h2>No schedule baseline</h2><p>Review tasks and resources, validate the DAG, then run CP-SAT.</p><button className="button button-primary" onClick={() => setTab("inputs")}>Open baseline setup</button></section> : <section className="surface schedule-board"><header><div><span className={`source-status ${["OPTIMAL", "FEASIBLE"].includes(current.solverStatus) ? "processed" : "pending"}`}>{current.solverStatus}</span><h2>Version {current.versionNumber}</h2><p>{current.solverVersion} · generated {new Intl.DateTimeFormat("en-IN", { dateStyle: "medium", timeStyle: "short" }).format(new Date(current.createdAt))}</p></div><button className="button button-secondary" onClick={solve} disabled={saving}><RefreshCw size={15} /> Controlled re-baseline</button></header>{current.overrunHours > 0 && <div className="infeasibility-banner"><AlertTriangle /><div><b>Minimum deadline overrun: {current.overrunHours} hours</b><p>{(current.bottlenecks as string[]).join(" ")}</p></div></div>}<div className="gantt">{gantt.map((item) => <div className="gantt-row" id={`task-${item.taskId}`} key={item.id}><span><b>{item.taskName}</b><small>{item.isCritical ? "Critical path" : "Scheduled"}</small></span><div className="gantt-track"><i className={item.isCritical ? "critical" : ""} style={{ left: `${item.left}%`, width: `${item.width}%` }} /></div><small>{new Intl.DateTimeFormat("en-IN", { month: "short", day: "numeric", hour: "numeric" }).format(new Date(item.startAt))}</small></div>)}</div><div className="ai-explanation"><span>AI-generated explanation · advisory only</span><p>{current.explanation ?? "Explanation is processing or failed; deterministic dates remain authoritative."}</p><small>{current.explanationModelVersion ?? "No model output"}</small></div></section>)}
    {tab === "history" && <section className="two-column"><article className="surface workflow-card"><p className="eyebrow">Append-only schedule</p><h2>Version history</h2>{versions.map((version, index) => <div className={`version-row ${version.id === focusVersionId ? "is-selected" : ""}`} id={`version-${version.id}`} key={version.id}><div><b>Version {version.versionNumber}</b><span>{version.reason}</span><small>{version.solverStatus} · {version.objectiveHours ?? "—"} h · {version.overrunHours} h overrun</small></div>{index < versions.length - 1 && <button className="icon-button" aria-label={`Compare version ${version.versionNumber}`} onClick={() => compare(version.id, versions[index + 1].id)}><GitCompareArrows size={16} /></button>}</div>)}</article><article className="surface workflow-card"><p className="eyebrow">Deterministic diff</p><h2>{diff ? `Version ${diff.current.versionNumber} vs ${diff.against?.versionNumber ?? "origin"}` : "Select two versions"}</h2>{diff && <><div className="metric-inline"><span>Net finish impact</span><b>{diff.netDeadlineImpactHours >= 0 ? "+" : ""}{diff.netDeadlineImpactHours} h</b></div>{diff.shiftedTasks.map((item) => <div className="entity-row" key={item.taskId}><div><b>{item.taskName}</b><span>{new Intl.DateTimeFormat("en-IN", { dateStyle: "medium", timeStyle: "short" }).format(new Date(item.beforeEnd))} → {new Intl.DateTimeFormat("en-IN", { dateStyle: "medium", timeStyle: "short" }).format(new Date(item.afterEnd))}</span></div><small>{item.shiftHours >= 0 ? "+" : ""}{item.shiftHours} h</small></div>)}</>}</article></section>}
    {tab === "events" && <section className="surface workflow-card"><div className="section-heading"><div><p className="eyebrow">Durable event pipeline</p><h2>Event history</h2></div></div>{events.map((event) => <article className="entity-row" key={event.id}><div><b>{event.eventType.replaceAll("_", " ")}</b><span>{new Intl.DateTimeFormat("en-IN", { dateStyle: "medium", timeStyle: "short" }).format(new Date(event.occurredAt))}{event.processingError ? ` · ${event.processingError}` : ""}</span></div><span className={`source-status ${event.processingStatus === "resolved" || event.processingStatus === "status_only" ? "processed" : "pending"}`}>{event.processingStatus.replaceAll("_", " ")}</span></article>)}{!events.length && <div className="empty-state"><CheckCircle2 /><h2>No schedule events yet</h2><p>Shipment transitions will appear here after a baseline exists.</p></div>}</section>}
  </div>;
}
