"use client";
import { useState } from "react";
import { FilePenLine, Save, ShieldAlert } from "lucide-react";
import { starterTemplates } from "@/lib/technology/starter-templates";

export function TechnologyDraftStudio({ projectId, initialCount }: { projectId: string; initialCount: number }) {
  const [templateId, setTemplateId] = useState(starterTemplates[0].id); const [draft, setDraft] = useState(starterTemplates[0]); const [status, setStatus] = useState(`${initialCount} saved project draft${initialCount === 1 ? "" : "s"}.`); const [saving, setSaving] = useState(false);
  const choose = (id: string) => { const next = starterTemplates.find((template) => template.id === id) ?? starterTemplates[0]; setTemplateId(next.id); setDraft(next); setStatus(`${next.label} placeholder loaded. Replace every bracketed or generic value before review.`); };
  const save = async () => { setSaving(true); try { const response = await fetch(`/api/projects/${projectId}/technology-drafts`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ templateId, category: draft.category, solutionName: draft.solutionName, summary: draft.summary, evidenceChecklist: draft.evidenceChecklist, claims: [draft.claim], parameters: [draft.parameter], commercialChecklist: draft.commercialChecklist }) }); const body = await response.json(); if (!response.ok) throw new Error(body.error); setStatus("Draft saved for human review. It is not a selectable or publishable plugin."); } catch (error) { setStatus(error instanceof Error ? error.message : "Unable to save draft."); } finally { setSaving(false); } };
  return <section className="technology-studio"><section className="technology-notice"><ShieldAlert size={18} /><div><b>Starter templates are non-production scaffolds.</b><p>They prefill a working draft only. Vendors must replace placeholders with their own cited evidence before a human review; no template can become a selectable plugin.</p></div></section><section className="technology-compose surface"><header><div><p className="eyebrow">Partner onboarding · draft only</p><h2>Technology Draft Studio</h2><p>Pick a category to prefill the draft, evidence checklist, first claim, first parameter, and commercial checklist.</p></div><FilePenLine size={25} /></header><label>Category starter<select value={templateId} onChange={(event) => choose(event.target.value)}>{starterTemplates.map((template) => <option value={template.id} key={template.id}>{template.category} · {template.label}</option>)}</select></label><div className="technology-grid"><label>Solution name<input value={draft.solutionName} onChange={(event) => setDraft({ ...draft, solutionName: event.target.value })} /></label><label>Category<input value={draft.category} onChange={(event) => setDraft({ ...draft, category: event.target.value })} /></label><label className="technology-full">Draft summary<textarea value={draft.summary} onChange={(event) => setDraft({ ...draft, summary: event.target.value })} /></label></div><DraftList title="Evidence checklist" items={draft.evidenceChecklist} /><DraftList title="Commercial checklist" items={draft.commercialChecklist} /><section className="technology-pair"><article><p className="eyebrow">First evidence-backed claim</p><b>{draft.claim.type}</b><p>{draft.claim.text}</p><small>Required: {draft.claim.evidenceRequired}</small></article><article><p className="eyebrow">First model parameter</p><b>{draft.parameter.label} · {draft.parameter.unit}</b><p>{draft.parameter.sourceHint}</p></article></section><div className="technology-actions"><p role="status">{status}</p><button className="button button-primary" type="button" onClick={save} disabled={saving}><Save size={16} />{saving ? "Saving…" : "Save controlled draft"}</button></div></section></section>;
}
function DraftList({ title, items }: { title: string; items: string[] }) { return <section className="technology-list"><p className="eyebrow">{title}</p><ul>{items.map((item) => <li key={item}>{item}</li>)}</ul></section>; }
