import { createHash } from "node:crypto";
import { and, asc, desc, eq } from "drizzle-orm";
import { NextResponse } from "next/server";
import { z } from "zod";
import { writeAuditEvent } from "@/lib/audit/write-event";
import { db } from "@/lib/db/client";
import { auditEvents, decisions, documentVersions, documents, edges, evidence, gates, projects, scheduleAssignments, scheduleVersions, storageObjects, turnoverPacks } from "@/lib/db/schema";
import { AccessError, requireProjectPermission } from "@/lib/projects/access";
import { projectObjectContentUrl } from "@/lib/storage/http";
import { objectStorage } from "@/lib/storage/service";
import { canonicalJson } from "@/lib/crypto/canonical-json";
import { selectApprovedCxRecordsForManifest } from "@/lib/cx/acceptance";
import { READINESS_RULE_VERSION } from "@/lib/readiness/project-readiness";
import { enforceExportRateLimit } from "@/lib/redis/rate-limit";
const schema = z.object({ gateId: z.string().uuid() });

export async function GET(_: Request, { params }: { params: Promise<{ projectId: string }> }) { const { projectId } = await params; try { await requireProjectPermission(projectId, "audit:view"); return NextResponse.json({ items: await db.select().from(turnoverPacks).where(eq(turnoverPacks.projectId, projectId)) }); } catch (error) { return NextResponse.json({ error: error instanceof Error ? error.message : "Unable to load turnover packs." }, { status: error instanceof AccessError ? error.status : 500 }); } }

export async function POST(request: Request, { params }: { params: Promise<{ projectId: string }> }) {
  const { projectId } = await params; const parsed = schema.safeParse(await request.json().catch(() => null)); if (!parsed.success) return NextResponse.json({ error: "A gate is required." }, { status: 400 });
  try {
    const limited = await enforceExportRateLimit(`turnover-packs:${projectId}`);
    if (limited) return limited;
    const actor = await requireProjectPermission(projectId, "gate:approve"); const project = await db.query.projects.findFirst({ where: eq(projects.id, projectId) }); const gate = await db.query.gates.findFirst({ where: and(eq(gates.id, parsed.data.gateId), eq(gates.projectId, projectId)) }); if (!project || !gate) return NextResponse.json({ error: "Project or gate not found." }, { status: 404 }); if (gate.status !== "approved") return NextResponse.json({ error: "Only an approved gate can be exported." }, { status: 409 });
    const decision = await db.query.decisions.findFirst({ where: and(eq(decisions.gateId, gate.id), eq(decisions.projectId, projectId)), orderBy: (table, { desc }) => [desc(table.decidedAt)] }); if (!decision || !["approve", "waive"].includes(decision.decision)) return NextResponse.json({ error: "An approval decision is required." }, { status: 409 });
    const [evidenceRows, sourceRows, graphEdges, auditRows, cxRecords, scheduleVersion] = await Promise.all([db.select().from(evidence).where(and(eq(evidence.projectId, projectId), eq(evidence.validityState, "accepted"))), db.select({ id: documentVersions.id, revision: documentVersions.revision, sha256: documentVersions.sha256, documentId: documents.id, title: documents.title, extractionModel: documentVersions.extractionModel, extractionProvider: documentVersions.extractionProvider }).from(documentVersions).innerJoin(documents, eq(documentVersions.documentId, documents.id)).where(eq(documents.projectId, projectId)), db.select().from(edges).where(eq(edges.projectId, projectId)), db.select().from(auditEvents).where(eq(auditEvents.projectId, projectId)).orderBy(asc(auditEvents.createdAt)), selectApprovedCxRecordsForManifest(projectId), db.query.scheduleVersions.findFirst({ where: eq(scheduleVersions.projectId, projectId), orderBy: [desc(scheduleVersions.versionNumber)] })]);
    const scheduleSnapshotAssignments = scheduleVersion ? await db.select({ taskId: scheduleAssignments.taskId, startAt: scheduleAssignments.startAt, endAt: scheduleAssignments.endAt, isCritical: scheduleAssignments.isCritical }).from(scheduleAssignments).where(eq(scheduleAssignments.versionId, scheduleVersion.id)) : [];
    const scheduleSnapshot = scheduleVersion ? { versionNumber: scheduleVersion.versionNumber, solverStatus: scheduleVersion.solverStatus, solverVersion: scheduleVersion.solverVersion, objectiveHours: scheduleVersion.objectiveHours, inputHash: scheduleVersion.inputHash, criticalTaskIds: [...(scheduleVersion.criticalTaskIds as string[])].sort(), explanationModelVersion: scheduleVersion.explanationModelVersion, assignments: scheduleSnapshotAssignments.map((item) => ({ taskId: item.taskId, startAt: item.startAt.toISOString(), endAt: item.endAt.toISOString(), isCritical: item.isCritical })).sort((a, b) => a.taskId.localeCompare(b.taskId)) } : null;
    const manifest = { schemaVersion: "1.0", generatedAt: new Date().toISOString(), readinessRuleVersion: READINESS_RULE_VERSION, project: { id: project.id, code: project.code, name: project.name }, gate: { id: gate.id, name: gate.name }, decision: { id: decision.id, decision: decision.decision, reason: decision.reason, evidenceBaselineHash: decision.evidenceBaselineHash, decidedAt: decision.decidedAt.toISOString() }, sources: sourceRows.sort((a, b) => a.id.localeCompare(b.id)), evidence: evidenceRows.map((item) => ({ id: item.id, type: item.evidenceType, contentHash: item.contentHash, capturedAt: item.capturedAt.toISOString(), validityState: item.validityState })).sort((a, b) => a.id.localeCompare(b.id)), cxRecords, edges: graphEdges.map((item) => ({ fromType: item.fromType, fromId: item.fromId, relationshipType: item.relationshipType, toType: item.toType, toId: item.toId })).sort((a, b) => `${a.fromId}:${a.toId}`.localeCompare(`${b.fromId}:${b.toId}`)), ...(scheduleSnapshot ? { scheduleSnapshot } : {}), auditChainHead: auditRows.at(-1)?.eventHash ?? null };
    const bytes = Buffer.from(canonicalJson(manifest)); const manifestHash = createHash("sha256").update(bytes).digest("hex"); const stored = await objectStorage.put({ tenantId: project.tenantId, projectId, bytes, mediaType: "application/json", fileName: `turnover-${gate.id}.json` });
    const transaction = await db.transaction(async (tx) => { const [pack] = await tx.insert(turnoverPacks).values({ tenantId: project.tenantId, projectId, gateId: gate.id, decisionId: decision.id, manifest, manifestHash, objectKey: stored.objectKey, createdBy: actor.userId }).returning(); const [object] = await tx.insert(storageObjects).values({ tenantId: project.tenantId, projectId, objectKey: stored.objectKey, mediaType: stored.mediaType, byteSize: stored.byteSize, sha256: stored.sha256, createdBy: actor.userId }).returning(); return { pack, object }; });
    const { pack } = transaction;
    await writeAuditEvent({ projectId, actorId: actor.userId, action: "turnover.generated", entityType: "turnover_pack", entityId: pack.id, after: { manifestHash, objectKey: stored.objectKey } });
    return NextResponse.json({ pack, verified: manifestHash === stored.sha256, downloadUrl: projectObjectContentUrl(projectId, transaction.object.id, request.url) }, { status: 201 });
  } catch (error) { return NextResponse.json({ error: error instanceof Error ? error.message : "Unable to generate turnover pack." }, { status: error instanceof AccessError ? error.status : 500 }); }
}
