import { desc, eq, inArray } from "drizzle-orm";
import { NextResponse } from "next/server";
import { z } from "zod";
import { db } from "@/lib/db/client";
import { scheduleAssignments, scheduleTasks, scheduleVersions } from "@/lib/db/schema";
import { AccessError, requireProjectPermission } from "@/lib/projects/access";
import { createScheduleVersion } from "@/lib/schedule/create-version";
import { enforceScheduleRateLimit } from "@/lib/redis/rate-limit";
const schema = z.object({ horizonStart: z.string().datetime(), reason: z.string().trim().min(5).max(2000) });
export async function GET(_: Request, { params }: { params: Promise<{ projectId: string }> }) { const { projectId } = await params; try { await requireProjectPermission(projectId, "audit:view"); const versions = await db.select().from(scheduleVersions).where(eq(scheduleVersions.projectId, projectId)).orderBy(desc(scheduleVersions.versionNumber)); const assignments = versions.length ? await db.select({ id: scheduleAssignments.id, versionId: scheduleAssignments.versionId, taskId: scheduleTasks.id, taskName: scheduleTasks.name, startAt: scheduleAssignments.startAt, endAt: scheduleAssignments.endAt, isCritical: scheduleAssignments.isCritical }).from(scheduleAssignments).innerJoin(scheduleTasks, eq(scheduleAssignments.taskId, scheduleTasks.id)).where(inArray(scheduleAssignments.versionId, versions.map((item) => item.id))) : []; return NextResponse.json({ versions: versions.map((version) => ({ ...version, assignments: assignments.filter((item) => item.versionId === version.id) })) }); } catch (error) { return NextResponse.json({ error: error instanceof Error ? error.message : "Unable to load schedule versions." }, { status: error instanceof AccessError ? error.status : 500 }); } }
export async function POST(request: Request, { params }: { params: Promise<{ projectId: string }> }) { const { projectId } = await params; const limited = await enforceScheduleRateLimit(`versions:${projectId}`); if (limited) return limited; const parsed = schema.safeParse(await request.json().catch(() => null)); if (!parsed.success) return NextResponse.json({ error: "A horizon start and solve reason are required." }, { status: 400 }); try { const actor = await requireProjectPermission(projectId, "schedule:manage"); const result = await createScheduleVersion({ projectId, actorId: actor.userId, horizonStart: new Date(parsed.data.horizonStart), reason: parsed.data.reason }); return NextResponse.json(result, { status: result.solver.status === "INFEASIBLE" ? 422 : 201 }); } catch (error) { return NextResponse.json({ error: error instanceof Error ? error.message : "Unable to solve schedule." }, { status: error instanceof AccessError ? error.status : error instanceof Error && error.message.includes("cycle") ? 409 : 502 }); } }
