export type StarterTemplate = { id: string; category: string; label: string; solutionName: string; summary: string; evidenceChecklist: string[]; claim: { type: string; text: string; evidenceRequired: string }; parameter: { key: string; label: string; unit: string; sourceHint: string }; commercialChecklist: string[] };
const baseCommercial = [
  "Unit and extended pricing with taxes, freight, packing and exclusions identified",
  "Quotation validity, currency, payment milestones and escalation basis",
  "Manufacturing and delivery lead time by exact model family",
  "Incoterms, delivery location, logistics constraints and delivery schedule",
  "Standard and extended warranty terms with commencement trigger",
  "Service coverage, escalation path and response / restoration targets",
  "Installation, testing, commissioning and acceptance responsibility matrix",
  "Recommended spares, consumables, special tools and training",
  "Deviations, substitutions, approved equivalents and commercial assumptions",
  "Comparable installed-base references and regional support capability",
];
export const starterTemplates: StarterTemplate[] = [
  { id: "cooling-liquid-heat-rejection-starter", category: "Cooling", label: "Cooling technology", solutionName: "[Vendor] cooling solution", summary: "Replace with the exact cooling architecture, system boundary, supported rack density, operating temperatures, heat-rejection path, water basis, and model inputs.", evidenceChecklist: ["System technical specification", "Product datasheet", "Installation drawing", "Performance curves", "Cooling SLD or P&ID"], claim: { type: "PUE impact", text: "Replace with evidence-backed PUE impact and applicable conditions.", evidenceRequired: "Performance curve or reference test report" }, parameter: { key: "pue_delta", label: "PUE impact", unit: "delta", sourceHint: "Curve, test report, or vendor-confirmed calculation" }, commercialChecklist: baseCommercial },
  { id: "power-generation-microgrid-starter", category: "Power", label: "Power / microgrid", solutionName: "[Vendor] power solution", summary: "Replace with electrical boundary, operating mode, fuel/grid dependency, ride-through behavior, emissions scope, controls interface, and model inputs.", evidenceChecklist: ["Electrical technical specification", "Power SLD", "Electrical study", "Operating-mode narrative", "Interconnect requirements"], claim: { type: "Resilience impact", text: "Replace with evidence-backed resilience and grid-load impact.", evidenceRequired: "Electrical study or reference test report" }, parameter: { key: "grid_load_delta_mw", label: "Grid load impact", unit: "MW", sourceHint: "Load-flow study or verified calculation" }, commercialChecklist: baseCommercial },
  { id: "it-oem-starter", category: "IT / OEM", label: "IT / OEM technology", solutionName: "[Vendor] IT platform", summary: "Replace with rack density, power envelope, thermal profile, network interfaces, operating limits, and dependencies Livio should model.", evidenceChecklist: ["Product datasheet", "Rack power profile", "Thermal envelope", "Network architecture", "Support matrix"], claim: { type: "Rack density", text: "Replace with supported density and operating boundary.", evidenceRequired: "OEM datasheet or lab validation" }, parameter: { key: "rack_density_kw", label: "Rack density", unit: "kW/rack", sourceHint: "OEM rating with ambient condition" }, commercialChecklist: baseCommercial },
  { id: "electrical-infrastructure-starter", category: "Electrical Infrastructure", label: "Electrical infrastructure", solutionName: "[Vendor] electrical infrastructure", summary: "Replace with capacity, redundancy, protection, harmonics, distribution boundary, maintenance modes, and model inputs.", evidenceChecklist: ["Technical specification", "Single-line diagram", "Protection study", "Harmonic study", "Equipment datasheets"], claim: { type: "Availability impact", text: "Replace with evidence-backed availability or redundancy impact.", evidenceRequired: "SLD and electrical study" }, parameter: { key: "redundancy_delta", label: "Redundancy impact", unit: "tier", sourceHint: "Controlled design and failure-mode analysis" }, commercialChecklist: baseCommercial },
  { id: "mechanical-water-starter", category: "Mechanical / Water", label: "Mechanical / water", solutionName: "[Vendor] mechanical water solution", summary: "Replace with water balance, mechanical boundary, quality needs, treatment requirements, reliability limits, and model inputs.", evidenceChecklist: ["Water balance", "Mechanical datasheet", "P&ID", "Water-quality requirements", "Performance curves"], claim: { type: "Water demand impact", text: "Replace with evidence-backed annual and peak water impact.", evidenceRequired: "Water balance or performance curve" }, parameter: { key: "water_demand_delta_pct", label: "Water demand impact", unit: "%", sourceHint: "Design condition and baseline required" }, commercialChecklist: baseCommercial },
  { id: "controls-software-starter", category: "Controls / Software", label: "Controls / software", solutionName: "[Vendor] controls platform", summary: "Replace with system boundary, integrations, data ownership, cybersecurity, controls sequence, and measured operational impact.", evidenceChecklist: ["Architecture diagram", "Interface specification", "Cybersecurity controls", "Sequence of operation", "Reference deployment evidence"], claim: { type: "Operational efficiency", text: "Replace with evidence-backed operational efficiency impact.", evidenceRequired: "Measured reference deployment or validated model" }, parameter: { key: "opex_delta_pct", label: "Operating-cost impact", unit: "%", sourceHint: "Baseline and measurement period required" }, commercialChecklist: baseCommercial },
  { id: "procurement-starter", category: "Procurement", label: "Procurement solution", solutionName: "[Vendor] procurement solution", summary: "Replace with supply scope, manufacturer status, lead-time logic, alternates, logistics route, risk controls, and commercial basis.", evidenceChecklist: ["Bill of materials", "Vendor quotations", "Lead-time evidence", "Logistics plan", "Warranty terms"], claim: { type: "Lead-time impact", text: "Replace with evidence-backed lead-time impact.", evidenceRequired: "Supplier confirmation or executed PO history" }, parameter: { key: "schedule_delta_weeks", label: "Schedule impact", unit: "weeks", sourceHint: "Supplier lead-time basis required" }, commercialChecklist: baseCommercial },
  { id: "permitting-advisory-starter", category: "Permitting / Advisory", label: "Permitting / advisory", solutionName: "[Vendor] permitting advisory", summary: "Replace with jurisdiction, permit path, assumptions, authority engagement, critical dependencies, and schedule-risk basis.", evidenceChecklist: ["Permit matrix", "Jurisdiction memo", "Submission schedule", "Authority correspondence", "Comparable approval evidence"], claim: { type: "Permit risk impact", text: "Replace with evidence-backed permit path and risk reduction.", evidenceRequired: "Jurisdiction memo or comparable approval record" }, parameter: { key: "permit_risk_delta", label: "Permit risk impact", unit: "score", sourceHint: "Jurisdiction-specific evidence required" }, commercialChecklist: baseCommercial }
];
