import { eq } from "drizzle-orm";
import { NextResponse } from "next/server";
import { z } from "zod";
import { writeAuditEvent } from "@/lib/audit/write-event";
import { db } from "@/lib/db/client";
import { financialModels } from "@/lib/db/schema";
import { AccessError, requireProjectPermission } from "@/lib/projects/access";

const schema = z.object({ contractedPowerMw: z.number().min(0.1).max(500), utilizationPct: z.number().min(1).max(100), leaseRateUsdMwMonth: z.number().min(0).max(5_000_000), powerCostUsdKwh: z.number().min(0).max(10), planningBudgetUsdMw: z.number().min(0).max(100_000_000), pue: z.number().min(1).max(3), discountRatePct: z.number().min(0).max(100), analysisPeriodYears: z.number().int().min(1).max(50), usdInrRate: z.number().min(1).max(1_000) });

export async function GET(_: Request, { params }: { params: Promise<{ projectId: string }> }) { const { projectId } = await params; try { await requireProjectPermission(projectId, "audit:view"); return NextResponse.json({ model: await db.query.financialModels.findFirst({ where: eq(financialModels.projectId, projectId) }) ?? null }); } catch (error) { return NextResponse.json({ error: error instanceof Error ? error.message : "Unable to load financial model." }, { status: error instanceof AccessError ? error.status : 500 }); } }

export async function PUT(request: Request, { params }: { params: Promise<{ projectId: string }> }) { const { projectId } = await params; const parsed = schema.safeParse(await request.json().catch(() => null)); if (!parsed.success) return NextResponse.json({ error: "Financial assumptions are invalid.", issues: parsed.error.flatten() }, { status: 400 }); try { const actor = await requireProjectPermission(projectId, "configuration:manage"); const input = parsed.data; const values = { contractedPowerMw: String(input.contractedPowerMw), utilizationPct: String(input.utilizationPct), leaseRateUsdMwMonth: String(input.leaseRateUsdMwMonth), powerCostUsdKwh: String(input.powerCostUsdKwh), planningBudgetUsdMw: String(input.planningBudgetUsdMw), pue: String(input.pue), discountRatePct: String(input.discountRatePct), analysisPeriodYears: input.analysisPeriodYears, usdInrRate: String(input.usdInrRate) }; const [model] = await db.insert(financialModels).values({ projectId, ...values }).onConflictDoUpdate({ target: financialModels.projectId, set: { ...values, updatedAt: new Date() } }).returning(); await writeAuditEvent({ projectId, actorId: actor.userId, action: "financial_model.saved", entityType: "financial_model", entityId: model.id, after: { canonicalCurrency: "USD", inputs: values } }); return NextResponse.json({ model }); } catch (error) { return NextResponse.json({ error: error instanceof Error ? error.message : "Unable to save financial model." }, { status: error instanceof AccessError ? error.status : 500 }); } }
