import { NextResponse } from "next/server";
import { eq } from "drizzle-orm";
import { z } from "zod";
import { randomUUID } from "node:crypto";
import { processScheduleEvent } from "@/lib/events/process";
import { db } from "@/lib/db/client";
import { shipments } from "@/lib/db/schema";
import { AccessError, requireProjectPermission } from "@/lib/projects/access";
import { calculateShipmentStatus } from "@/lib/supply/status";

const schema = z.object({ name: z.string().min(3).max(200), plannedEta: z.string().datetime(), requiredOnSite: z.string().datetime(), portCongestion: z.boolean().default(false) });
export async function GET(_: Request, { params }: { params: Promise<{ projectId: string }> }) { const { projectId } = await params; try { await requireProjectPermission(projectId, "audit:view"); return NextResponse.json({ items: await db.select().from(shipments).where(eq(shipments.projectId, projectId)), estimate: true }); } catch (error) { return NextResponse.json({ error: error instanceof Error ? error.message : "Unable to load shipments" }, { status: error instanceof AccessError ? error.status : 500 }); } }
export async function POST(request: Request, { params }: { params: Promise<{ projectId: string }> }) { const { projectId } = await params; const parsed = schema.safeParse(await request.json().catch(() => null)); if (!parsed.success) return NextResponse.json({ error: "Invalid shipment" }, { status: 400 }); try { const actor = await requireProjectPermission(projectId, "schedule:manage"); const project = await db.query.projects.findFirst({ where: (projects, { eq }) => eq(projects.id, projectId) }); if (!project) return NextResponse.json({ error: "Project not found" }, { status: 404 }); const calculated = calculateShipmentStatus({ plannedEta: new Date(parsed.data.plannedEta), requiredOnSite: new Date(parsed.data.requiredOnSite), portCongestion: parsed.data.portCongestion }); const [shipment] = await db.insert(shipments).values({ tenantId: project.tenantId, projectId, name: parsed.data.name, plannedEta: new Date(parsed.data.plannedEta), weatherAdjustedEta: calculated.weatherAdjustedEta, requiredOnSite: new Date(parsed.data.requiredOnSite), portCongestion: parsed.data.portCongestion, status: calculated.status, lastNotifiedStatus: calculated.status, createdBy: actor.userId }).returning(); if (calculated.status !== "green") await processScheduleEvent({ eventId: randomUUID(), projectId, occurredAt: new Date().toISOString(), transitionId: `created-${calculated.status}`, eventType: "SHIPMENT_DELAYED", payload: { shipmentId: shipment.id, status: calculated.status, affectedTaskIds: [], estimate: true } }, actor.userId); return NextResponse.json({ shipment, positionSource: "simulated", estimate: true }, { status: 201 }); } catch (error) { return NextResponse.json({ error: error instanceof Error ? error.message : "Unable to create shipment" }, { status: error instanceof AccessError ? error.status : 500 }); } }
