import type { ComponentType } from "react";
import { GateReadinessTable } from "./gate-readiness-table";
import { FindingList } from "./finding-list";
import { AlertList } from "./alert-list";
import { CitationList } from "./citation-list";
import { EntropyPanel } from "./entropy-panel";
import { ProjectOverview } from "./project-overview";
import { ShipmentTable } from "./shipment-table";
import { ShipmentDetail } from "./shipment-detail";
import { ScheduleTimeline } from "./schedule-timeline";
import { ChecklistSteps } from "./checklist-steps";
import { ComplianceSummary } from "./compliance-summary";
import { Download } from "./download";

/**
 * Props every registered renderer component receives: the `data` payload from the
 * matching `CopilotRender` in the response envelope (`src/lib/copilot/types.ts`).
 * Renderer files define this shape inline (`{ data: unknown }`) rather than importing
 * it from here, to avoid a circular import with this index.
 */
export type CopilotRendererProps = { data: unknown };

/**
 * Registry of renderer components, keyed by `CopilotRender.key` (e.g. "gateReadinessTable").
 * `copilot-message.tsx` looks up each render by key here and falls back to a raw JSON
 * dump when a key isn't registered.
 *
 * FILE OWNERSHIP — READ BEFORE EDITING: this is the pre-declared renderer index, written
 * ONCE (Wave 1/2 reconciliation) and never edited again, mirroring
 * `src/lib/copilot/registry/index.ts`. Every renderer module this build needs is already
 * imported above and listed below. Later agents (Slice 6 batches, and Slice 10's
 * `download` renderer) do NOT edit this file — they only edit their OWN renderer file
 * (e.g. `./gate-readiness-table.tsx`), replacing its placeholder JSON-dump body with a
 * real component. If a genuinely new renderer key is ever needed beyond this list, that
 * is a new-file-plus-index-line change requiring the same care as adding a new registry
 * module — treat it as an exception, not the normal path.
 */
export const rendererRegistry: Record<string, ComponentType<CopilotRendererProps>> = {
  gateReadinessTable: GateReadinessTable,
  findingList: FindingList,
  alertList: AlertList,
  citationList: CitationList,
  entropyPanel: EntropyPanel,
  projectOverview: ProjectOverview,
  shipmentTable: ShipmentTable,
  shipmentDetail: ShipmentDetail,
  scheduleTimeline: ScheduleTimeline,
  checklistSteps: ChecklistSteps,
  complianceSummary: ComplianceSummary,
  download: Download,
};
